//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod non_conformance_bulk;
pub mod quality_action_bulk;
pub mod quality_inspection_bulk;
pub mod quality_inspection_reading_bulk;
pub mod quality_inspection_template_bulk;
pub mod quality_inspection_parameter_bulk;
pub mod quality_procedure_bulk;

pub use non_conformance_bulk::NonConformanceBulkService;
pub use quality_action_bulk::QualityActionBulkService;
pub use quality_inspection_bulk::QualityInspectionBulkService;
pub use quality_inspection_reading_bulk::QualityInspectionReadingBulkService;
pub use quality_inspection_template_bulk::QualityInspectionTemplateBulkService;
pub use quality_inspection_parameter_bulk::QualityInspectionParameterBulkService;
pub use quality_procedure_bulk::QualityProcedureBulkService;

// <<< CUSTOM
// END CUSTOM
