//! Bulk operations for NonConformance entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateNonConformanceDto;
use crate::application::service::NonConformanceService;
use crate::domain::entity::NonConformance;

/// Bulk operation handler for NonConformance entities.
///
/// Wraps `NonConformanceService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type NonConformanceBulkService = GenericBulkService<NonConformance, CreateNonConformanceDto, NonConformanceService>;

// <<< CUSTOM
// END CUSTOM
