//! Bulk operations for QualityProcedure entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateQualityProcedureDto;
use crate::application::service::QualityProcedureService;
use crate::domain::entity::QualityProcedure;

/// Bulk operation handler for QualityProcedure entities.
///
/// Wraps `QualityProcedureService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type QualityProcedureBulkService = GenericBulkService<QualityProcedure, CreateQualityProcedureDto, QualityProcedureService>;

// <<< CUSTOM
// END CUSTOM
