//! Bulk operations for QualityInspectionReading entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateQualityInspectionReadingDto;
use crate::application::service::QualityInspectionReadingService;
use crate::domain::entity::QualityInspectionReading;

/// Bulk operation handler for QualityInspectionReading entities.
///
/// Wraps `QualityInspectionReadingService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type QualityInspectionReadingBulkService = GenericBulkService<QualityInspectionReading, CreateQualityInspectionReadingDto, QualityInspectionReadingService>;

// <<< CUSTOM
// END CUSTOM
