//! Bulk operations for QualityInspectionParameter entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateQualityInspectionParameterDto;
use crate::application::service::QualityInspectionParameterService;
use crate::domain::entity::QualityInspectionParameter;

/// Bulk operation handler for QualityInspectionParameter entities.
///
/// Wraps `QualityInspectionParameterService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type QualityInspectionParameterBulkService = GenericBulkService<QualityInspectionParameter, CreateQualityInspectionParameterDto, QualityInspectionParameterService>;

// <<< CUSTOM
// END CUSTOM
