//! Bulk operations for QualityInspection entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateQualityInspectionDto;
use crate::application::service::QualityInspectionService;
use crate::domain::entity::QualityInspection;

/// Bulk operation handler for QualityInspection entities.
///
/// Wraps `QualityInspectionService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type QualityInspectionBulkService = GenericBulkService<QualityInspection, CreateQualityInspectionDto, QualityInspectionService>;

// <<< CUSTOM
// END CUSTOM
