//! Bulk operations for QualityAction entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateQualityActionDto;
use crate::application::service::QualityActionService;
use crate::domain::entity::QualityAction;

/// Bulk operation handler for QualityAction entities.
///
/// Wraps `QualityActionService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type QualityActionBulkService = GenericBulkService<QualityAction, CreateQualityActionDto, QualityActionService>;

// <<< CUSTOM
// END CUSTOM
