//! Bulk operations for QualityInspectionTemplate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateQualityInspectionTemplateDto;
use crate::application::service::QualityInspectionTemplateService;
use crate::domain::entity::QualityInspectionTemplate;

/// Bulk operation handler for QualityInspectionTemplate entities.
///
/// Wraps `QualityInspectionTemplateService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type QualityInspectionTemplateBulkService = GenericBulkService<QualityInspectionTemplate, CreateQualityInspectionTemplateDto, QualityInspectionTemplateService>;

// <<< CUSTOM
// END CUSTOM
