//! NonConformance DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::NonConformance;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::NonConformanceSeverity;
use crate::domain::entity::NonConformanceStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new NonConformance
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateNonConformanceDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub subject: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "source_inspection_id")]
    pub source_inspection_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    pub severity: NonConformanceSeverity,
    pub status: NonConformanceStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 4000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "opened_at")]
    pub opened_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "closed_at")]
    pub closed_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a NonConformance
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateNonConformanceDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub subject: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "source_inspection_id")]
    pub source_inspection_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    pub severity: NonConformanceSeverity,
    pub status: NonConformanceStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 4000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "opened_at")]
    pub opened_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "closed_at")]
    pub closed_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a NonConformance
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchNonConformanceDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "source_inspection_id")]
    pub source_inspection_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub severity: Option<NonConformanceSeverity>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<NonConformanceStatus>,
    #[cfg_attr(feature = "validation", validate(length(max = 4000)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "opened_at")]
    pub opened_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "closed_at")]
    pub closed_at: Option<DateTime<Utc>>,
}

impl PatchNonConformanceDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.subject.is_some() || self.source_inspection_id.is_some() || self.item_id.is_some() || self.severity.is_some() || self.status.is_some() || self.description.is_some() || self.opened_at.is_some() || self.closed_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for NonConformance entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct NonConformanceResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub subject: String,
    pub source_inspection_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub severity: NonConformanceSeverity,
    pub status: NonConformanceStatus,
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub opened_at: DateTime<Utc>,
    pub closed_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for NonConformance entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct NonConformanceListResponseDto {
    /// List of items
    pub items: Vec<NonConformanceResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl NonConformanceListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<NonConformanceResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct NonConformanceSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub subject: String,
    pub source_inspection_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<NonConformance> for NonConformanceResponseDto {
    fn from(entity: NonConformance) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            subject: entity.subject,
            source_inspection_id: entity.source_inspection_id,
            item_id: entity.item_id,
            severity: entity.severity,
            status: entity.status,
            description: entity.description,
            opened_at: entity.opened_at,
            closed_at: entity.closed_at,
            metadata: entity.metadata,
        }
    }
}

impl From<NonConformance> for NonConformanceSummaryDto {
    fn from(entity: NonConformance) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            subject: entity.subject,
            source_inspection_id: entity.source_inspection_id,
            created_at,
        }
    }
}

impl From<CreateNonConformanceDto> for NonConformance {
    fn from(dto: CreateNonConformanceDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            subject: dto.subject,
            source_inspection_id: dto.source_inspection_id,
            item_id: dto.item_id,
            severity: dto.severity,
            status: dto.status,
            description: dto.description,
            opened_at: dto.opened_at,
            closed_at: dto.closed_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&NonConformance> for NonConformanceResponseDto {
    fn from(entity: &NonConformance) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            subject: entity.subject.clone(),
            source_inspection_id: entity.source_inspection_id.clone(),
            item_id: entity.item_id.clone(),
            severity: entity.severity.clone(),
            status: entity.status.clone(),
            description: entity.description.clone(),
            opened_at: entity.opened_at.clone(),
            closed_at: entity.closed_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateNonConformanceDto> for NonConformance {
    fn from_create_dto(dto: CreateNonConformanceDto) -> backbone_core::ServiceResult<Self> {
        Ok(NonConformance::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateNonConformanceDto> for NonConformance {
    fn apply_update(mut self, dto: UpdateNonConformanceDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.subject = dto.subject;
        self.source_inspection_id = dto.source_inspection_id;
        self.item_id = dto.item_id;
        self.severity = dto.severity;
        self.status = dto.status;
        self.description = dto.description;
        self.opened_at = dto.opened_at;
        self.closed_at = dto.closed_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to NonConformance here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
