//! QualityProcedure DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::QualityProcedure;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new QualityProcedure
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateQualityProcedureDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "procedure_name")]
    pub procedure_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "parent_procedure_id")]
    pub parent_procedure_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 4000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a QualityProcedure
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateQualityProcedureDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "procedure_name")]
    pub procedure_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "parent_procedure_id")]
    pub parent_procedure_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 4000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a QualityProcedure
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchQualityProcedureDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "procedure_name")]
    pub procedure_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "parent_procedure_id")]
    pub parent_procedure_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 4000)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_active")]
    pub is_active: Option<bool>,
}

impl PatchQualityProcedureDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.procedure_name.is_some() || self.parent_procedure_id.is_some() || self.description.is_some() || self.is_active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for QualityProcedure entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct QualityProcedureResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub procedure_name: String,
    pub parent_procedure_id: Option<Uuid>,
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for QualityProcedure entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct QualityProcedureListResponseDto {
    /// List of items
    pub items: Vec<QualityProcedureResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl QualityProcedureListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<QualityProcedureResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct QualityProcedureSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub procedure_name: String,
    pub parent_procedure_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<QualityProcedure> for QualityProcedureResponseDto {
    fn from(entity: QualityProcedure) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            procedure_name: entity.procedure_name,
            parent_procedure_id: entity.parent_procedure_id,
            description: entity.description,
            is_active: entity.is_active,
            metadata: entity.metadata,
        }
    }
}

impl From<QualityProcedure> for QualityProcedureSummaryDto {
    fn from(entity: QualityProcedure) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            procedure_name: entity.procedure_name,
            parent_procedure_id: entity.parent_procedure_id,
            created_at,
        }
    }
}

impl From<CreateQualityProcedureDto> for QualityProcedure {
    fn from(dto: CreateQualityProcedureDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            procedure_name: dto.procedure_name,
            parent_procedure_id: dto.parent_procedure_id,
            description: dto.description,
            is_active: dto.is_active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&QualityProcedure> for QualityProcedureResponseDto {
    fn from(entity: &QualityProcedure) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            procedure_name: entity.procedure_name.clone(),
            parent_procedure_id: entity.parent_procedure_id.clone(),
            description: entity.description.clone(),
            is_active: entity.is_active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateQualityProcedureDto> for QualityProcedure {
    fn from_create_dto(dto: CreateQualityProcedureDto) -> backbone_core::ServiceResult<Self> {
        Ok(QualityProcedure::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateQualityProcedureDto> for QualityProcedure {
    fn apply_update(mut self, dto: UpdateQualityProcedureDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.procedure_name = dto.procedure_name;
        self.parent_procedure_id = dto.parent_procedure_id;
        self.description = dto.description;
        self.is_active = dto.is_active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to QualityProcedure here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
