//! QualityAction DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::QualityAction;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::QualityActionStatus;
use crate::domain::entity::QualityActionType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new QualityAction
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateQualityActionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "non_conformance_id")]
    pub non_conformance_id: Uuid,
    #[serde(alias = "action_type")]
    pub action_type: QualityActionType,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "procedure_id")]
    pub procedure_id: Option<Uuid>,
    pub status: QualityActionStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub description: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "due_date")]
    pub due_date: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "completed_at")]
    pub completed_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a QualityAction
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateQualityActionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "non_conformance_id")]
    pub non_conformance_id: Uuid,
    #[serde(alias = "action_type")]
    pub action_type: QualityActionType,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "procedure_id")]
    pub procedure_id: Option<Uuid>,
    pub status: QualityActionStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub description: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "due_date")]
    pub due_date: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "completed_at")]
    pub completed_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a QualityAction
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchQualityActionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "non_conformance_id")]
    pub non_conformance_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "action_type")]
    pub action_type: Option<QualityActionType>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "procedure_id")]
    pub procedure_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<QualityActionStatus>,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "due_date")]
    pub due_date: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "completed_at")]
    pub completed_at: Option<DateTime<Utc>>,
}

impl PatchQualityActionDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.non_conformance_id.is_some() || self.action_type.is_some() || self.procedure_id.is_some() || self.status.is_some() || self.description.is_some() || self.due_date.is_some() || self.completed_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for QualityAction entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct QualityActionResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub non_conformance_id: Uuid,
    pub action_type: QualityActionType,
    pub procedure_id: Option<Uuid>,
    pub status: QualityActionStatus,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub description: String,
    pub due_date: Option<DateTime<Utc>>,
    pub completed_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for QualityAction entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct QualityActionListResponseDto {
    /// List of items
    pub items: Vec<QualityActionResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl QualityActionListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<QualityActionResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct QualityActionSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub non_conformance_id: Uuid,
    pub action_type: QualityActionType,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<QualityAction> for QualityActionResponseDto {
    fn from(entity: QualityAction) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            non_conformance_id: entity.non_conformance_id,
            action_type: entity.action_type,
            procedure_id: entity.procedure_id,
            status: entity.status,
            description: entity.description,
            due_date: entity.due_date,
            completed_at: entity.completed_at,
            metadata: entity.metadata,
        }
    }
}

impl From<QualityAction> for QualityActionSummaryDto {
    fn from(entity: QualityAction) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            non_conformance_id: entity.non_conformance_id,
            action_type: entity.action_type,
            created_at,
        }
    }
}

impl From<CreateQualityActionDto> for QualityAction {
    fn from(dto: CreateQualityActionDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            non_conformance_id: dto.non_conformance_id,
            action_type: dto.action_type,
            procedure_id: dto.procedure_id,
            status: dto.status,
            description: dto.description,
            due_date: dto.due_date,
            completed_at: dto.completed_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&QualityAction> for QualityActionResponseDto {
    fn from(entity: &QualityAction) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            non_conformance_id: entity.non_conformance_id.clone(),
            action_type: entity.action_type.clone(),
            procedure_id: entity.procedure_id.clone(),
            status: entity.status.clone(),
            description: entity.description.clone(),
            due_date: entity.due_date.clone(),
            completed_at: entity.completed_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateQualityActionDto> for QualityAction {
    fn from_create_dto(dto: CreateQualityActionDto) -> backbone_core::ServiceResult<Self> {
        Ok(QualityAction::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateQualityActionDto> for QualityAction {
    fn apply_update(mut self, dto: UpdateQualityActionDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.non_conformance_id = dto.non_conformance_id;
        self.action_type = dto.action_type;
        self.procedure_id = dto.procedure_id;
        self.status = dto.status;
        self.description = dto.description;
        self.due_date = dto.due_date;
        self.completed_at = dto.completed_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to QualityAction here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
