//! QualityInspectionParameter DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::QualityInspectionParameter;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new QualityInspectionParameter
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateQualityInspectionParameterDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "template_id")]
    pub template_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "parameter_name")]
    pub parameter_name: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub numeric: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "min_value")]
    pub min_value: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "max_value")]
    pub max_value: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "spec_text")]
    pub spec_text: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a QualityInspectionParameter
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateQualityInspectionParameterDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "template_id")]
    pub template_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "parameter_name")]
    pub parameter_name: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub numeric: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "min_value")]
    pub min_value: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "max_value")]
    pub max_value: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "spec_text")]
    pub spec_text: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a QualityInspectionParameter
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchQualityInspectionParameterDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "template_id")]
    pub template_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "parameter_name")]
    pub parameter_name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub numeric: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "min_value")]
    pub min_value: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "max_value")]
    pub max_value: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "spec_text")]
    pub spec_text: Option<String>,
}

impl PatchQualityInspectionParameterDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.template_id.is_some() || self.parameter_name.is_some() || self.numeric.is_some() || self.min_value.is_some() || self.max_value.is_some() || self.spec_text.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for QualityInspectionParameter entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct QualityInspectionParameterResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub template_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub parameter_name: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub numeric: bool,
    pub min_value: Option<Decimal>,
    pub max_value: Option<Decimal>,
    pub spec_text: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for QualityInspectionParameter entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct QualityInspectionParameterListResponseDto {
    /// List of items
    pub items: Vec<QualityInspectionParameterResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl QualityInspectionParameterListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<QualityInspectionParameterResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct QualityInspectionParameterSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub template_id: Uuid,
    pub parameter_name: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<QualityInspectionParameter> for QualityInspectionParameterResponseDto {
    fn from(entity: QualityInspectionParameter) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            template_id: entity.template_id,
            parameter_name: entity.parameter_name,
            numeric: entity.numeric,
            min_value: entity.min_value,
            max_value: entity.max_value,
            spec_text: entity.spec_text,
            metadata: entity.metadata,
        }
    }
}

impl From<QualityInspectionParameter> for QualityInspectionParameterSummaryDto {
    fn from(entity: QualityInspectionParameter) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            template_id: entity.template_id,
            parameter_name: entity.parameter_name,
            created_at,
        }
    }
}

impl From<CreateQualityInspectionParameterDto> for QualityInspectionParameter {
    fn from(dto: CreateQualityInspectionParameterDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            template_id: dto.template_id,
            parameter_name: dto.parameter_name,
            numeric: dto.numeric,
            min_value: dto.min_value,
            max_value: dto.max_value,
            spec_text: dto.spec_text,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&QualityInspectionParameter> for QualityInspectionParameterResponseDto {
    fn from(entity: &QualityInspectionParameter) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            template_id: entity.template_id.clone(),
            parameter_name: entity.parameter_name.clone(),
            numeric: entity.numeric.clone(),
            min_value: entity.min_value.clone(),
            max_value: entity.max_value.clone(),
            spec_text: entity.spec_text.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateQualityInspectionParameterDto> for QualityInspectionParameter {
    fn from_create_dto(dto: CreateQualityInspectionParameterDto) -> backbone_core::ServiceResult<Self> {
        Ok(QualityInspectionParameter::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateQualityInspectionParameterDto> for QualityInspectionParameter {
    fn apply_update(mut self, dto: UpdateQualityInspectionParameterDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.template_id = dto.template_id;
        self.parameter_name = dto.parameter_name;
        self.numeric = dto.numeric;
        self.min_value = dto.min_value;
        self.max_value = dto.max_value;
        self.spec_text = dto.spec_text;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to QualityInspectionParameter here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
