//! QualityInspection DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::QualityInspection;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::InspectionStatus;
use crate::domain::entity::InspectionType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new QualityInspection
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateQualityInspectionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "template_id")]
    pub template_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[serde(alias = "inspection_type")]
    pub inspection_type: InspectionType,
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "source_type")]
    pub source_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "source_id")]
    pub source_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "sample_size")]
    pub sample_size: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "inspected_at")]
    pub inspected_at: DateTime<Utc>,
    pub status: InspectionStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remarks: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a QualityInspection
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateQualityInspectionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "template_id")]
    pub template_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[serde(alias = "inspection_type")]
    pub inspection_type: InspectionType,
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "source_type")]
    pub source_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "source_id")]
    pub source_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "sample_size")]
    pub sample_size: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "inspected_at")]
    pub inspected_at: DateTime<Utc>,
    pub status: InspectionStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remarks: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a QualityInspection
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchQualityInspectionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "template_id")]
    pub template_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "inspection_type")]
    pub inspection_type: Option<InspectionType>,
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "source_type")]
    pub source_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "source_id")]
    pub source_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "sample_size")]
    pub sample_size: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "inspected_at")]
    pub inspected_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<InspectionStatus>,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub remarks: Option<String>,
}

impl PatchQualityInspectionDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.template_id.is_some() || self.item_id.is_some() || self.inspection_type.is_some() || self.source_type.is_some() || self.source_id.is_some() || self.sample_size.is_some() || self.inspected_at.is_some() || self.status.is_some() || self.remarks.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for QualityInspection entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct QualityInspectionResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub template_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub item_id: Uuid,
    pub inspection_type: InspectionType,
    pub source_type: Option<String>,
    pub source_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sample_size: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub inspected_at: DateTime<Utc>,
    pub status: InspectionStatus,
    pub remarks: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for QualityInspection entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct QualityInspectionListResponseDto {
    /// List of items
    pub items: Vec<QualityInspectionResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl QualityInspectionListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<QualityInspectionResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct QualityInspectionSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub template_id: Option<Uuid>,
    pub item_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<QualityInspection> for QualityInspectionResponseDto {
    fn from(entity: QualityInspection) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            template_id: entity.template_id,
            item_id: entity.item_id,
            inspection_type: entity.inspection_type,
            source_type: entity.source_type,
            source_id: entity.source_id,
            sample_size: entity.sample_size,
            inspected_at: entity.inspected_at,
            status: entity.status,
            remarks: entity.remarks,
            metadata: entity.metadata,
        }
    }
}

impl From<QualityInspection> for QualityInspectionSummaryDto {
    fn from(entity: QualityInspection) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            template_id: entity.template_id,
            item_id: entity.item_id,
            created_at,
        }
    }
}

impl From<CreateQualityInspectionDto> for QualityInspection {
    fn from(dto: CreateQualityInspectionDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            template_id: dto.template_id,
            item_id: dto.item_id,
            inspection_type: dto.inspection_type,
            source_type: dto.source_type,
            source_id: dto.source_id,
            sample_size: dto.sample_size,
            inspected_at: dto.inspected_at,
            status: dto.status,
            remarks: dto.remarks,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&QualityInspection> for QualityInspectionResponseDto {
    fn from(entity: &QualityInspection) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            template_id: entity.template_id.clone(),
            item_id: entity.item_id.clone(),
            inspection_type: entity.inspection_type.clone(),
            source_type: entity.source_type.clone(),
            source_id: entity.source_id.clone(),
            sample_size: entity.sample_size.clone(),
            inspected_at: entity.inspected_at.clone(),
            status: entity.status.clone(),
            remarks: entity.remarks.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateQualityInspectionDto> for QualityInspection {
    fn from_create_dto(dto: CreateQualityInspectionDto) -> backbone_core::ServiceResult<Self> {
        Ok(QualityInspection::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateQualityInspectionDto> for QualityInspection {
    fn apply_update(mut self, dto: UpdateQualityInspectionDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.template_id = dto.template_id;
        self.item_id = dto.item_id;
        self.inspection_type = dto.inspection_type;
        self.source_type = dto.source_type;
        self.source_id = dto.source_id;
        self.sample_size = dto.sample_size;
        self.inspected_at = dto.inspected_at;
        self.status = dto.status;
        self.remarks = dto.remarks;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to QualityInspection here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
