//! QualityInspectionReading DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::QualityInspectionReading;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::ReadingResult;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new QualityInspectionReading
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateQualityInspectionReadingDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "inspection_id")]
    pub inspection_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "parameter_name")]
    pub parameter_name: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub numeric: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reading_value")]
    pub reading_value: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "min_value")]
    pub min_value: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "max_value")]
    pub max_value: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "manual_result")]
    pub manual_result: Option<bool>,
    pub result: ReadingResult,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remarks: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a QualityInspectionReading
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateQualityInspectionReadingDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "inspection_id")]
    pub inspection_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "parameter_name")]
    pub parameter_name: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub numeric: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reading_value")]
    pub reading_value: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "min_value")]
    pub min_value: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "max_value")]
    pub max_value: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "manual_result")]
    pub manual_result: Option<bool>,
    pub result: ReadingResult,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remarks: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a QualityInspectionReading
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchQualityInspectionReadingDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "inspection_id")]
    pub inspection_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "parameter_name")]
    pub parameter_name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub numeric: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "reading_value")]
    pub reading_value: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "min_value")]
    pub min_value: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "max_value")]
    pub max_value: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "manual_result")]
    pub manual_result: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<ReadingResult>,
    #[cfg_attr(feature = "validation", validate(length(max = 280)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub remarks: Option<String>,
}

impl PatchQualityInspectionReadingDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.inspection_id.is_some() || self.parameter_name.is_some() || self.numeric.is_some() || self.reading_value.is_some() || self.min_value.is_some() || self.max_value.is_some() || self.manual_result.is_some() || self.result.is_some() || self.remarks.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for QualityInspectionReading entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct QualityInspectionReadingResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub inspection_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub parameter_name: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub numeric: bool,
    pub reading_value: Option<Decimal>,
    pub min_value: Option<Decimal>,
    pub max_value: Option<Decimal>,
    pub manual_result: Option<bool>,
    pub result: ReadingResult,
    pub remarks: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for QualityInspectionReading entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct QualityInspectionReadingListResponseDto {
    /// List of items
    pub items: Vec<QualityInspectionReadingResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl QualityInspectionReadingListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<QualityInspectionReadingResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct QualityInspectionReadingSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub inspection_id: Uuid,
    pub parameter_name: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<QualityInspectionReading> for QualityInspectionReadingResponseDto {
    fn from(entity: QualityInspectionReading) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            inspection_id: entity.inspection_id,
            parameter_name: entity.parameter_name,
            numeric: entity.numeric,
            reading_value: entity.reading_value,
            min_value: entity.min_value,
            max_value: entity.max_value,
            manual_result: entity.manual_result,
            result: entity.result,
            remarks: entity.remarks,
            metadata: entity.metadata,
        }
    }
}

impl From<QualityInspectionReading> for QualityInspectionReadingSummaryDto {
    fn from(entity: QualityInspectionReading) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            inspection_id: entity.inspection_id,
            parameter_name: entity.parameter_name,
            created_at,
        }
    }
}

impl From<CreateQualityInspectionReadingDto> for QualityInspectionReading {
    fn from(dto: CreateQualityInspectionReadingDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            inspection_id: dto.inspection_id,
            parameter_name: dto.parameter_name,
            numeric: dto.numeric,
            reading_value: dto.reading_value,
            min_value: dto.min_value,
            max_value: dto.max_value,
            manual_result: dto.manual_result,
            result: dto.result,
            remarks: dto.remarks,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&QualityInspectionReading> for QualityInspectionReadingResponseDto {
    fn from(entity: &QualityInspectionReading) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            inspection_id: entity.inspection_id.clone(),
            parameter_name: entity.parameter_name.clone(),
            numeric: entity.numeric.clone(),
            reading_value: entity.reading_value.clone(),
            min_value: entity.min_value.clone(),
            max_value: entity.max_value.clone(),
            manual_result: entity.manual_result.clone(),
            result: entity.result.clone(),
            remarks: entity.remarks.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateQualityInspectionReadingDto> for QualityInspectionReading {
    fn from_create_dto(dto: CreateQualityInspectionReadingDto) -> backbone_core::ServiceResult<Self> {
        Ok(QualityInspectionReading::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateQualityInspectionReadingDto> for QualityInspectionReading {
    fn apply_update(mut self, dto: UpdateQualityInspectionReadingDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.inspection_id = dto.inspection_id;
        self.parameter_name = dto.parameter_name;
        self.numeric = dto.numeric;
        self.reading_value = dto.reading_value;
        self.min_value = dto.min_value;
        self.max_value = dto.max_value;
        self.manual_result = dto.manual_result;
        self.result = dto.result;
        self.remarks = dto.remarks;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to QualityInspectionReading here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
