//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod non_conformance_specification;
pub mod quality_action_specification;
pub mod quality_inspection_specification;
pub mod quality_inspection_reading_specification;
pub mod quality_inspection_template_specification;
pub mod quality_inspection_parameter_specification;
pub mod quality_procedure_specification;

// <<< CUSTOM
// END CUSTOM
