//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod non_conformance_domain_policy;
pub mod quality_action_domain_policy;
pub mod quality_inspection_domain_policy;
pub mod quality_inspection_reading_domain_policy;
pub mod quality_inspection_template_domain_policy;
pub mod quality_inspection_parameter_domain_policy;
pub mod quality_procedure_domain_policy;

pub use non_conformance_domain_policy::NonConformanceDomainPolicy;
pub use quality_action_domain_policy::QualityActionDomainPolicy;
pub use quality_inspection_domain_policy::QualityInspectionDomainPolicy;
pub use quality_inspection_reading_domain_policy::QualityInspectionReadingDomainPolicy;
pub use quality_inspection_template_domain_policy::QualityInspectionTemplateDomainPolicy;
pub use quality_inspection_parameter_domain_policy::QualityInspectionParameterDomainPolicy;
pub use quality_procedure_domain_policy::QualityProcedureDomainPolicy;

// <<< CUSTOM
// END CUSTOM
