//! Domain policy for QualityInspectionReading aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::QualityInspectionReading;

/// Domain policy for QualityInspectionReading — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<QualityInspectionReading>` in the `// <<< CUSTOM` zone.
pub type QualityInspectionReadingDomainPolicy = PermitAllPolicy<QualityInspectionReading>;

// <<< CUSTOM
// END CUSTOM
