//! Domain policy for QualityInspectionTemplate aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::QualityInspectionTemplate;

/// Domain policy for QualityInspectionTemplate — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<QualityInspectionTemplate>` in the `// <<< CUSTOM` zone.
pub type QualityInspectionTemplateDomainPolicy = PermitAllPolicy<QualityInspectionTemplate>;

// <<< CUSTOM
// END CUSTOM
