//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod non_conformance_service;
pub mod quality_action_service;
pub mod quality_inspection_service;
pub mod quality_inspection_reading_service;
pub mod quality_inspection_template_service;
pub mod quality_inspection_parameter_service;
pub mod quality_procedure_service;

// <<< CUSTOM
pub mod quality_events;
pub mod quality_write_service;
// END CUSTOM

pub use non_conformance_service::NonConformanceService;
pub use quality_action_service::QualityActionService;
pub use quality_inspection_service::QualityInspectionService;
pub use quality_inspection_reading_service::QualityInspectionReadingService;
pub use quality_inspection_template_service::QualityInspectionTemplateService;
pub use quality_inspection_parameter_service::QualityInspectionParameterService;
pub use quality_procedure_service::QualityProcedureService;
// <<< CUSTOM
pub use quality_events::{
    LoggingSink, NonConformanceClosed, NonConformanceRaised, QualityEvent, QualityEventSink,
    QualityInspectionCompleted,
};
pub use quality_write_service::{
    InspectOutcome, NewInspection, NewNonConformance, NewProcedure, NewQualityAction, NewReading,
    NewTemplate, NewTemplateParameter, QualityError, QualityWriteService,
};
// END CUSTOM