//! Application service for NonConformance entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `non_conformance_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateNonConformanceDto, UpdateNonConformanceDto};
use crate::domain::entity::NonConformance;
use crate::infrastructure::persistence::NonConformanceRepository;

/// Application service for NonConformance entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `non_conformance_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct NonConformanceServiceCustom {
///     inner: Arc<NonConformanceService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type NonConformanceService = GenericCrudService<
    NonConformance,
    CreateNonConformanceDto,
    UpdateNonConformanceDto,
    NonConformanceRepository,
>;

// <<< CUSTOM
// END CUSTOM
