//! Application service for QualityInspectionReading entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `quality_inspection_reading_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateQualityInspectionReadingDto, UpdateQualityInspectionReadingDto};
use crate::domain::entity::QualityInspectionReading;
use crate::infrastructure::persistence::QualityInspectionReadingRepository;

/// Application service for QualityInspectionReading entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `quality_inspection_reading_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct QualityInspectionReadingServiceCustom {
///     inner: Arc<QualityInspectionReadingService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type QualityInspectionReadingService = GenericCrudService<
    QualityInspectionReading,
    CreateQualityInspectionReadingDto,
    UpdateQualityInspectionReadingDto,
    QualityInspectionReadingRepository,
>;

// <<< CUSTOM
// END CUSTOM
