//! Application service for QualityInspectionTemplate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `quality_inspection_template_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateQualityInspectionTemplateDto, UpdateQualityInspectionTemplateDto};
use crate::domain::entity::QualityInspectionTemplate;
use crate::infrastructure::persistence::QualityInspectionTemplateRepository;

/// Application service for QualityInspectionTemplate entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `quality_inspection_template_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct QualityInspectionTemplateServiceCustom {
///     inner: Arc<QualityInspectionTemplateService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type QualityInspectionTemplateService = GenericCrudService<
    QualityInspectionTemplate,
    CreateQualityInspectionTemplateDto,
    UpdateQualityInspectionTemplateDto,
    QualityInspectionTemplateRepository,
>;

// <<< CUSTOM
// END CUSTOM
