//! Application service for QualityAction entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `quality_action_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateQualityActionDto, UpdateQualityActionDto};
use crate::domain::entity::QualityAction;
use crate::infrastructure::persistence::QualityActionRepository;

/// Application service for QualityAction entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `quality_action_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct QualityActionServiceCustom {
///     inner: Arc<QualityActionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type QualityActionService = GenericCrudService<
    QualityAction,
    CreateQualityActionDto,
    UpdateQualityActionDto,
    QualityActionRepository,
>;

// <<< CUSTOM
// END CUSTOM
