//! Application service for QualityProcedure entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `quality_procedure_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateQualityProcedureDto, UpdateQualityProcedureDto};
use crate::domain::entity::QualityProcedure;
use crate::infrastructure::persistence::QualityProcedureRepository;

/// Application service for QualityProcedure entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `quality_procedure_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct QualityProcedureServiceCustom {
///     inner: Arc<QualityProcedureService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type QualityProcedureService = GenericCrudService<
    QualityProcedure,
    CreateQualityProcedureDto,
    UpdateQualityProcedureDto,
    QualityProcedureRepository,
>;

// <<< CUSTOM
// END CUSTOM
