//! Application service for QualityInspection entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `quality_inspection_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateQualityInspectionDto, UpdateQualityInspectionDto};
use crate::domain::entity::QualityInspection;
use crate::infrastructure::persistence::QualityInspectionRepository;

/// Application service for QualityInspection entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `quality_inspection_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct QualityInspectionServiceCustom {
///     inner: Arc<QualityInspectionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type QualityInspectionService = GenericCrudService<
    QualityInspection,
    CreateQualityInspectionDto,
    UpdateQualityInspectionDto,
    QualityInspectionRepository,
>;

// <<< CUSTOM
// END CUSTOM
