-- NonConformance Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the quality.non_conformances table.
-- Customize this file to add your initial data.

-- INSERT INTO quality.non_conformances (
--     id,
--     company_id,
--     subject,
--     source_inspection_id,
--     item_id,
--     severity,
--     status,
--     description,
--     opened_at,
--     closed_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO quality.non_conformances (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

