-- QualityInspectionParameter Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the quality.quality_inspection_parameters table.
-- Customize this file to add your initial data.

-- INSERT INTO quality.quality_inspection_parameters (
--     id,
--     template_id,
--     parameter_name,
--     numeric,
--     min_value,
--     max_value,
--     spec_text,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO quality.quality_inspection_parameters (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

