-- QualityAction Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the quality.quality_actions table.
-- Customize this file to add your initial data.

-- INSERT INTO quality.quality_actions (
--     id,
--     company_id,
--     non_conformance_id,
--     action_type,
--     procedure_id,
--     status,
--     description,
--     due_date,
--     completed_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO quality.quality_actions (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

