-- QualityInspection Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the quality.quality_inspections table.
-- Customize this file to add your initial data.

-- INSERT INTO quality.quality_inspections (
--     id,
--     company_id,
--     template_id,
--     item_id,
--     inspection_type,
--     source_type,
--     source_id,
--     sample_size,
--     inspected_at,
--     status,
--     remarks,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO quality.quality_inspections (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

