-- QualityInspectionReading Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the quality.quality_inspection_readings table.
-- Customize this file to add your initial data.

-- INSERT INTO quality.quality_inspection_readings (
--     id,
--     inspection_id,
--     parameter_name,
--     numeric,
--     reading_value,
--     min_value,
--     max_value,
--     manual_result,
--     result,
--     remarks,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO quality.quality_inspection_readings (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

