-- Migration: Create quality_procedures table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS quality;

CREATE TABLE IF NOT EXISTS quality.quality_procedures (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    procedure_name TEXT NOT NULL,
    parent_procedure_id UUID,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_quality_procedures_company_id_is_active ON quality.quality_procedures (company_id, is_active);

CREATE INDEX IF NOT EXISTS idx_quality_procedures_parent_procedure_id ON quality.quality_procedures (parent_procedure_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_quality_procedures_metadata_gin ON quality.quality_procedures USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_quality_procedures_metadata_deleted_at ON quality.quality_procedures ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_quality_procedures_metadata_created_at ON quality.quality_procedures ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_quality_procedures_metadata_updated_at ON quality.quality_procedures ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION quality.quality_procedures_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS quality_procedures_insert_audit ON quality.quality_procedures;
CREATE TRIGGER quality_procedures_insert_audit BEFORE INSERT ON quality.quality_procedures
    FOR EACH ROW EXECUTE FUNCTION quality.quality_procedures_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS quality_procedures_update_audit ON quality.quality_procedures;
CREATE TRIGGER quality_procedures_update_audit BEFORE UPDATE ON quality.quality_procedures
    FOR EACH ROW EXECUTE FUNCTION quality.quality_procedures_audit_timestamp();
