-- Migration: Create quality_inspection_readings table
-- Generated by metaphor-schema

-- Create reading_result enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reading_result') THEN
        CREATE TYPE reading_result AS ENUM ('accepted', 'rejected');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS quality;

CREATE TABLE IF NOT EXISTS quality.quality_inspection_readings (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    inspection_id UUID NOT NULL,
    parameter_name TEXT NOT NULL,
    numeric BOOLEAN NOT NULL DEFAULT TRUE,
    reading_value NUMERIC(18, 4),
    min_value NUMERIC(18, 4),
    max_value NUMERIC(18, 4),
    manual_result BOOLEAN,
    result reading_result NOT NULL DEFAULT 'accepted',
    remarks TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_quality_inspection_readings_inspection_id ON quality.quality_inspection_readings (inspection_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_quality_inspection_readings_metadata_gin ON quality.quality_inspection_readings USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_quality_inspection_readings_metadata_deleted_at ON quality.quality_inspection_readings ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_quality_inspection_readings_metadata_created_at ON quality.quality_inspection_readings ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_quality_inspection_readings_metadata_updated_at ON quality.quality_inspection_readings ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION quality.quality_inspection_readings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS quality_inspection_readings_insert_audit ON quality.quality_inspection_readings;
CREATE TRIGGER quality_inspection_readings_insert_audit BEFORE INSERT ON quality.quality_inspection_readings
    FOR EACH ROW EXECUTE FUNCTION quality.quality_inspection_readings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS quality_inspection_readings_update_audit ON quality.quality_inspection_readings;
CREATE TRIGGER quality_inspection_readings_update_audit BEFORE UPDATE ON quality.quality_inspection_readings
    FOR EACH ROW EXECUTE FUNCTION quality.quality_inspection_readings_audit_timestamp();
