-- Migration: Create quality_inspection_parameters table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS quality;

CREATE TABLE IF NOT EXISTS quality.quality_inspection_parameters (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    template_id UUID NOT NULL,
    parameter_name TEXT NOT NULL,
    numeric BOOLEAN NOT NULL DEFAULT TRUE,
    min_value NUMERIC,
    max_value NUMERIC,
    spec_text TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_quality_inspection_parameters_template_id ON quality.quality_inspection_parameters (template_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_quality_inspection_parameters_metadata_gin ON quality.quality_inspection_parameters USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_quality_inspection_parameters_metadata_deleted_at ON quality.quality_inspection_parameters ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_quality_inspection_parameters_metadata_created_at ON quality.quality_inspection_parameters ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_quality_inspection_parameters_metadata_updated_at ON quality.quality_inspection_parameters ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION quality.quality_inspection_parameters_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS quality_inspection_parameters_insert_audit ON quality.quality_inspection_parameters;
CREATE TRIGGER quality_inspection_parameters_insert_audit BEFORE INSERT ON quality.quality_inspection_parameters
    FOR EACH ROW EXECUTE FUNCTION quality.quality_inspection_parameters_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS quality_inspection_parameters_update_audit ON quality.quality_inspection_parameters;
CREATE TRIGGER quality_inspection_parameters_update_audit BEFORE UPDATE ON quality.quality_inspection_parameters
    FOR EACH ROW EXECUTE FUNCTION quality.quality_inspection_parameters_audit_timestamp();
