-- Migration: Create quality_inspections table
-- Generated by metaphor-schema

-- Create inspection_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'inspection_type') THEN
        CREATE TYPE inspection_type AS ENUM ('incoming', 'in_process', 'outgoing');
    END IF;
END
$$;

-- Create inspection_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'inspection_status') THEN
        CREATE TYPE inspection_status AS ENUM ('pending', 'accepted', 'rejected');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS quality;

CREATE TABLE IF NOT EXISTS quality.quality_inspections (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    template_id UUID,
    item_id UUID NOT NULL,
    inspection_type inspection_type NOT NULL DEFAULT 'incoming',
    source_type TEXT,
    source_id UUID,
    sample_size INTEGER NOT NULL DEFAULT 1,
    inspected_at TIMESTAMPTZ NOT NULL,
    status inspection_status NOT NULL DEFAULT 'pending',
    remarks TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_quality_inspections_company_id_status ON quality.quality_inspections (company_id, status);

CREATE INDEX IF NOT EXISTS idx_quality_inspections_item_id ON quality.quality_inspections (item_id);

CREATE INDEX IF NOT EXISTS idx_quality_inspections_source_type_source_id ON quality.quality_inspections (source_type, source_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_quality_inspections_metadata_gin ON quality.quality_inspections USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_quality_inspections_metadata_deleted_at ON quality.quality_inspections ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_quality_inspections_metadata_created_at ON quality.quality_inspections ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_quality_inspections_metadata_updated_at ON quality.quality_inspections ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION quality.quality_inspections_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS quality_inspections_insert_audit ON quality.quality_inspections;
CREATE TRIGGER quality_inspections_insert_audit BEFORE INSERT ON quality.quality_inspections
    FOR EACH ROW EXECUTE FUNCTION quality.quality_inspections_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS quality_inspections_update_audit ON quality.quality_inspections;
CREATE TRIGGER quality_inspections_update_audit BEFORE UPDATE ON quality.quality_inspections
    FOR EACH ROW EXECUTE FUNCTION quality.quality_inspections_audit_timestamp();
