-- Enum types for quality module
-- Generated by metaphor-schema

-- Create non_conformance_severity enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'non_conformance_severity') THEN
        CREATE TYPE non_conformance_severity AS ENUM ('low', 'medium', 'high', 'critical');
    END IF;
END
$$;

-- Create non_conformance_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'non_conformance_status') THEN
        CREATE TYPE non_conformance_status AS ENUM ('open', 'in_progress', 'closed');
    END IF;
END
$$;

-- Create quality_action_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'quality_action_type') THEN
        CREATE TYPE quality_action_type AS ENUM ('corrective', 'preventive');
    END IF;
END
$$;

-- Create quality_action_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'quality_action_status') THEN
        CREATE TYPE quality_action_status AS ENUM ('open', 'in_progress', 'completed');
    END IF;
END
$$;

-- Create inspection_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'inspection_type') THEN
        CREATE TYPE inspection_type AS ENUM ('incoming', 'in_process', 'outgoing');
    END IF;
END
$$;

-- Create inspection_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'inspection_status') THEN
        CREATE TYPE inspection_status AS ENUM ('pending', 'accepted', 'rejected');
    END IF;
END
$$;

-- Create reading_result enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reading_result') THEN
        CREATE TYPE reading_result AS ENUM ('accepted', 'rejected');
    END IF;
END
$$;

