-- Migration: Create quality_actions table
-- Generated by metaphor-schema

-- Create quality_action_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'quality_action_type') THEN
        CREATE TYPE quality_action_type AS ENUM ('corrective', 'preventive');
    END IF;
END
$$;

-- Create quality_action_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'quality_action_status') THEN
        CREATE TYPE quality_action_status AS ENUM ('open', 'in_progress', 'completed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS quality;

CREATE TABLE IF NOT EXISTS quality.quality_actions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    non_conformance_id UUID NOT NULL,
    action_type quality_action_type NOT NULL DEFAULT 'corrective',
    procedure_id UUID,
    status quality_action_status NOT NULL DEFAULT 'open',
    description TEXT NOT NULL,
    due_date TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_quality_actions_non_conformance_id_status ON quality.quality_actions (non_conformance_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_quality_actions_metadata_gin ON quality.quality_actions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_quality_actions_metadata_deleted_at ON quality.quality_actions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_quality_actions_metadata_created_at ON quality.quality_actions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_quality_actions_metadata_updated_at ON quality.quality_actions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION quality.quality_actions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS quality_actions_insert_audit ON quality.quality_actions;
CREATE TRIGGER quality_actions_insert_audit BEFORE INSERT ON quality.quality_actions
    FOR EACH ROW EXECUTE FUNCTION quality.quality_actions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS quality_actions_update_audit ON quality.quality_actions;
CREATE TRIGGER quality_actions_update_audit BEFORE UPDATE ON quality.quality_actions
    FOR EACH ROW EXECUTE FUNCTION quality.quality_actions_audit_timestamp();
