-- Migration: Create non_conformances table
-- Generated by metaphor-schema

-- Create non_conformance_severity enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'non_conformance_severity') THEN
        CREATE TYPE non_conformance_severity AS ENUM ('low', 'medium', 'high', 'critical');
    END IF;
END
$$;

-- Create non_conformance_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'non_conformance_status') THEN
        CREATE TYPE non_conformance_status AS ENUM ('open', 'in_progress', 'closed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS quality;

CREATE TABLE IF NOT EXISTS quality.non_conformances (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    subject TEXT NOT NULL,
    source_inspection_id UUID,
    item_id UUID,
    severity non_conformance_severity NOT NULL DEFAULT 'medium',
    status non_conformance_status NOT NULL DEFAULT 'open',
    description TEXT,
    opened_at TIMESTAMPTZ NOT NULL,
    closed_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_non_conformances_company_id_status ON quality.non_conformances (company_id, status);

CREATE INDEX IF NOT EXISTS idx_non_conformances_source_inspection_id ON quality.non_conformances (source_inspection_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_non_conformances_metadata_gin ON quality.non_conformances USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_non_conformances_metadata_deleted_at ON quality.non_conformances ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_non_conformances_metadata_created_at ON quality.non_conformances ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_non_conformances_metadata_updated_at ON quality.non_conformances ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION quality.non_conformances_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS non_conformances_insert_audit ON quality.non_conformances;
CREATE TRIGGER non_conformances_insert_audit BEFORE INSERT ON quality.non_conformances
    FOR EACH ROW EXECUTE FUNCTION quality.non_conformances_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS non_conformances_update_audit ON quality.non_conformances;
CREATE TRIGGER non_conformances_update_audit BEFORE UPDATE ON quality.non_conformances
    FOR EACH ROW EXECUTE FUNCTION quality.non_conformances_audit_timestamp();
