-- Audit Triggers Migration for quality module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: NonConformance (quality.non_conformances)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION quality.non_conformances_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS non_conformances_insert_audit ON quality.non_conformances;
CREATE TRIGGER non_conformances_insert_audit BEFORE INSERT ON quality.non_conformances
    FOR EACH ROW EXECUTE FUNCTION quality.non_conformances_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS non_conformances_update_audit ON quality.non_conformances;
CREATE TRIGGER non_conformances_update_audit BEFORE UPDATE ON quality.non_conformances
    FOR EACH ROW EXECUTE FUNCTION quality.non_conformances_audit_timestamp();

-- ==============================================================================
-- Table: QualityAction (quality.quality_actions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION quality.quality_actions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS quality_actions_insert_audit ON quality.quality_actions;
CREATE TRIGGER quality_actions_insert_audit BEFORE INSERT ON quality.quality_actions
    FOR EACH ROW EXECUTE FUNCTION quality.quality_actions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS quality_actions_update_audit ON quality.quality_actions;
CREATE TRIGGER quality_actions_update_audit BEFORE UPDATE ON quality.quality_actions
    FOR EACH ROW EXECUTE FUNCTION quality.quality_actions_audit_timestamp();

-- ==============================================================================
-- Table: QualityInspection (quality.quality_inspections)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION quality.quality_inspections_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS quality_inspections_insert_audit ON quality.quality_inspections;
CREATE TRIGGER quality_inspections_insert_audit BEFORE INSERT ON quality.quality_inspections
    FOR EACH ROW EXECUTE FUNCTION quality.quality_inspections_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS quality_inspections_update_audit ON quality.quality_inspections;
CREATE TRIGGER quality_inspections_update_audit BEFORE UPDATE ON quality.quality_inspections
    FOR EACH ROW EXECUTE FUNCTION quality.quality_inspections_audit_timestamp();

-- ==============================================================================
-- Table: QualityInspectionReading (quality.quality_inspection_readings)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION quality.quality_inspection_readings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS quality_inspection_readings_insert_audit ON quality.quality_inspection_readings;
CREATE TRIGGER quality_inspection_readings_insert_audit BEFORE INSERT ON quality.quality_inspection_readings
    FOR EACH ROW EXECUTE FUNCTION quality.quality_inspection_readings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS quality_inspection_readings_update_audit ON quality.quality_inspection_readings;
CREATE TRIGGER quality_inspection_readings_update_audit BEFORE UPDATE ON quality.quality_inspection_readings
    FOR EACH ROW EXECUTE FUNCTION quality.quality_inspection_readings_audit_timestamp();

-- ==============================================================================
-- Table: QualityInspectionTemplate (quality.quality_inspection_templates)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION quality.quality_inspection_templates_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS quality_inspection_templates_insert_audit ON quality.quality_inspection_templates;
CREATE TRIGGER quality_inspection_templates_insert_audit BEFORE INSERT ON quality.quality_inspection_templates
    FOR EACH ROW EXECUTE FUNCTION quality.quality_inspection_templates_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS quality_inspection_templates_update_audit ON quality.quality_inspection_templates;
CREATE TRIGGER quality_inspection_templates_update_audit BEFORE UPDATE ON quality.quality_inspection_templates
    FOR EACH ROW EXECUTE FUNCTION quality.quality_inspection_templates_audit_timestamp();

-- ==============================================================================
-- Table: QualityInspectionParameter (quality.quality_inspection_parameters)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION quality.quality_inspection_parameters_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS quality_inspection_parameters_insert_audit ON quality.quality_inspection_parameters;
CREATE TRIGGER quality_inspection_parameters_insert_audit BEFORE INSERT ON quality.quality_inspection_parameters
    FOR EACH ROW EXECUTE FUNCTION quality.quality_inspection_parameters_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS quality_inspection_parameters_update_audit ON quality.quality_inspection_parameters;
CREATE TRIGGER quality_inspection_parameters_update_audit BEFORE UPDATE ON quality.quality_inspection_parameters
    FOR EACH ROW EXECUTE FUNCTION quality.quality_inspection_parameters_audit_timestamp();

-- ==============================================================================
-- Table: QualityProcedure (quality.quality_procedures)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION quality.quality_procedures_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS quality_procedures_insert_audit ON quality.quality_procedures;
CREATE TRIGGER quality_procedures_insert_audit BEFORE INSERT ON quality.quality_procedures
    FOR EACH ROW EXECUTE FUNCTION quality.quality_procedures_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS quality_procedures_update_audit ON quality.quality_procedures;
CREATE TRIGGER quality_procedures_update_audit BEFORE UPDATE ON quality.quality_procedures
    FOR EACH ROW EXECUTE FUNCTION quality.quality_procedures_audit_timestamp();

