-- Company RLS fence for quality module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for quality.non_conformances
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE quality.non_conformances ENABLE ROW LEVEL SECURITY;
ALTER TABLE quality.non_conformances FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS non_conformances_company_isolation ON quality.non_conformances;
CREATE POLICY non_conformances_company_isolation ON quality.non_conformances
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for quality.quality_actions
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE quality.quality_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE quality.quality_actions FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS quality_actions_company_isolation ON quality.quality_actions;
CREATE POLICY quality_actions_company_isolation ON quality.quality_actions
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for quality.quality_inspections
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE quality.quality_inspections ENABLE ROW LEVEL SECURITY;
ALTER TABLE quality.quality_inspections FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS quality_inspections_company_isolation ON quality.quality_inspections;
CREATE POLICY quality_inspections_company_isolation ON quality.quality_inspections
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for quality.quality_inspection_templates
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE quality.quality_inspection_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE quality.quality_inspection_templates FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS quality_inspection_templates_company_isolation ON quality.quality_inspection_templates;
CREATE POLICY quality_inspection_templates_company_isolation ON quality.quality_inspection_templates
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for quality.quality_procedures
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE quality.quality_procedures ENABLE ROW LEVEL SECURITY;
ALTER TABLE quality.quality_procedures FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS quality_procedures_company_isolation ON quality.quality_procedures;
CREATE POLICY quality_procedures_company_isolation ON quality.quality_procedures
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

