//! Domain events for NonConformance entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::NonConformance;

/// Domain events for NonConformance — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<NonConformance>)` variant.
pub type NonConformanceEvent = CrudEvent<NonConformance>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for NonConformance events.
pub type NonConformanceEventPublisher = Arc<dyn CrudEventPublisher<NonConformance> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopNonConformanceEventPublisher = NoOpCrudEventPublisher<NonConformance>;
