//! Event handler trait for NonConformance events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::NonConformanceEvent;

/// Event handler for NonConformance events.
/// Implement this trait to react to NonConformance lifecycle events.
pub trait NonConformanceEventHandler: EventHandler<NonConformanceEvent> {}
