//! Domain events for QualityProcedure entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::QualityProcedure;

/// Domain events for QualityProcedure — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<QualityProcedure>)` variant.
pub type QualityProcedureEvent = CrudEvent<QualityProcedure>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for QualityProcedure events.
pub type QualityProcedureEventPublisher = Arc<dyn CrudEventPublisher<QualityProcedure> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopQualityProcedureEventPublisher = NoOpCrudEventPublisher<QualityProcedure>;
