//! Domain events for QualityInspectionTemplate entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::QualityInspectionTemplate;

/// Domain events for QualityInspectionTemplate — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<QualityInspectionTemplate>)` variant.
pub type QualityInspectionTemplateEvent = CrudEvent<QualityInspectionTemplate>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for QualityInspectionTemplate events.
pub type QualityInspectionTemplateEventPublisher = Arc<dyn CrudEventPublisher<QualityInspectionTemplate> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopQualityInspectionTemplateEventPublisher = NoOpCrudEventPublisher<QualityInspectionTemplate>;
