//! Event handler trait for QualityInspectionTemplate events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::QualityInspectionTemplateEvent;

/// Event handler for QualityInspectionTemplate events.
/// Implement this trait to react to QualityInspectionTemplate lifecycle events.
pub trait QualityInspectionTemplateEventHandler: EventHandler<QualityInspectionTemplateEvent> {}
