//! Event handler trait for QualityInspectionParameter events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::QualityInspectionParameterEvent;

/// Event handler for QualityInspectionParameter events.
/// Implement this trait to react to QualityInspectionParameter lifecycle events.
pub trait QualityInspectionParameterEventHandler: EventHandler<QualityInspectionParameterEvent> {}
