//! Domain events for QualityAction entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::QualityAction;

/// Domain events for QualityAction — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<QualityAction>)` variant.
pub type QualityActionEvent = CrudEvent<QualityAction>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for QualityAction events.
pub type QualityActionEventPublisher = Arc<dyn CrudEventPublisher<QualityAction> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopQualityActionEventPublisher = NoOpCrudEventPublisher<QualityAction>;
