//! Event handler trait for QualityInspectionReading events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::QualityInspectionReadingEvent;

/// Event handler for QualityInspectionReading events.
/// Implement this trait to react to QualityInspectionReading lifecycle events.
pub trait QualityInspectionReadingEventHandler: EventHandler<QualityInspectionReadingEvent> {}
