//! Event handler trait for QualityInspection events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::QualityInspectionEvent;

/// Event handler for QualityInspection events.
/// Implement this trait to react to QualityInspection lifecycle events.
pub trait QualityInspectionEventHandler: EventHandler<QualityInspectionEvent> {}
