//! Domain events for QualityInspection entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::QualityInspection;

/// Domain events for QualityInspection — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<QualityInspection>)` variant.
pub type QualityInspectionEvent = CrudEvent<QualityInspection>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for QualityInspection events.
pub type QualityInspectionEventPublisher = Arc<dyn CrudEventPublisher<QualityInspection> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopQualityInspectionEventPublisher = NoOpCrudEventPublisher<QualityInspection>;
