//! Event handler trait for QualityAction events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::QualityActionEvent;

/// Event handler for QualityAction events.
/// Implement this trait to react to QualityAction lifecycle events.
pub trait QualityActionEventHandler: EventHandler<QualityActionEvent> {}
