//! Event handler trait for QualityProcedure events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::QualityProcedureEvent;

/// Event handler for QualityProcedure events.
/// Implement this trait to react to QualityProcedure lifecycle events.
pub trait QualityProcedureEventHandler: EventHandler<QualityProcedureEvent> {}
