//! Event subscriber type aliases for Quality module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::NonConformanceEvent;
use crate::domain::event::QualityActionEvent;
use crate::domain::event::QualityInspectionEvent;
use crate::domain::event::QualityInspectionReadingEvent;
use crate::domain::event::QualityInspectionTemplateEvent;
use crate::domain::event::QualityInspectionParameterEvent;
use crate::domain::event::QualityProcedureEvent;

/// Subscriber for NonConformance events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type NonConformanceEventSubscriber = GenericEventSubscriber<NonConformanceEvent>;

/// Subscriber for QualityAction events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type QualityActionEventSubscriber = GenericEventSubscriber<QualityActionEvent>;

/// Subscriber for QualityInspection events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type QualityInspectionEventSubscriber = GenericEventSubscriber<QualityInspectionEvent>;

/// Subscriber for QualityInspectionReading events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type QualityInspectionReadingEventSubscriber = GenericEventSubscriber<QualityInspectionReadingEvent>;

/// Subscriber for QualityInspectionTemplate events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type QualityInspectionTemplateEventSubscriber = GenericEventSubscriber<QualityInspectionTemplateEvent>;

/// Subscriber for QualityInspectionParameter events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type QualityInspectionParameterEventSubscriber = GenericEventSubscriber<QualityInspectionParameterEvent>;

/// Subscriber for QualityProcedure events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type QualityProcedureEventSubscriber = GenericEventSubscriber<QualityProcedureEvent>;

// <<< CUSTOM
// END CUSTOM
