//! Quality Event Subscriptions
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Cross-module event subscriptions. Each entity subscriber is a type alias
//! over `GenericEventSubscriber` from backbone-messaging.

pub mod handlers;
pub mod registry;

pub use handlers::*;
pub use registry::SubscriptionRegistry;

pub use handlers::NonConformanceEventSubscriber;
pub use handlers::QualityActionEventSubscriber;
pub use handlers::QualityInspectionEventSubscriber;
pub use handlers::QualityInspectionReadingEventSubscriber;
pub use handlers::QualityInspectionTemplateEventSubscriber;
pub use handlers::QualityInspectionParameterEventSubscriber;
pub use handlers::QualityProcedureEventSubscriber;
