//! QualityProcedure seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial QualityProcedure data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// QUALITYPROCEDURE SEEDER
// ============================================================================

/// Seeder for quality_procedure
pub struct SeedQualityProcedureSeeder;

impl SeedQualityProcedureSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedQualityProcedureSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedQualityProcedureSeeder {
    fn name(&self) -> &'static str {
        "SeedQualityProcedureSeeder"
    }

    fn order(&self) -> i32 {
        7
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if quality.quality_procedures table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM quality.quality_procedures")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/quality_procedure_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM quality.quality_procedures")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

