//! QualityInspection seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial QualityInspection data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// QUALITYINSPECTION SEEDER
// ============================================================================

/// Seeder for quality_inspection
pub struct SeedQualityInspectionSeeder;

impl SeedQualityInspectionSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedQualityInspectionSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedQualityInspectionSeeder {
    fn name(&self) -> &'static str {
        "SeedQualityInspectionSeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if quality.quality_inspections table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM quality.quality_inspections")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/quality_inspection_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM quality.quality_inspections")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

