//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod non_conformance_repository;
pub mod quality_action_repository;
pub mod quality_inspection_repository;
pub mod quality_inspection_reading_repository;
pub mod quality_inspection_template_repository;
pub mod quality_inspection_parameter_repository;
pub mod quality_procedure_repository;

// Re-exports
pub use non_conformance_repository::{
    NonConformanceRepository,
    NonConformancePaginationParams,
    NonConformancePaginatedResult,
    NonConformanceFilter,
};
pub use quality_action_repository::{
    QualityActionRepository,
    QualityActionPaginationParams,
    QualityActionPaginatedResult,
    QualityActionFilter,
};
pub use quality_inspection_repository::{
    QualityInspectionRepository,
    QualityInspectionPaginationParams,
    QualityInspectionPaginatedResult,
    QualityInspectionFilter,
};
pub use quality_inspection_reading_repository::{
    QualityInspectionReadingRepository,
    QualityInspectionReadingPaginationParams,
    QualityInspectionReadingPaginatedResult,
    QualityInspectionReadingFilter,
};
pub use quality_inspection_template_repository::{
    QualityInspectionTemplateRepository,
    QualityInspectionTemplatePaginationParams,
    QualityInspectionTemplatePaginatedResult,
    QualityInspectionTemplateFilter,
};
pub use quality_inspection_parameter_repository::{
    QualityInspectionParameterRepository,
    QualityInspectionParameterPaginationParams,
    QualityInspectionParameterPaginatedResult,
    QualityInspectionParameterFilter,
};
pub use quality_procedure_repository::{
    QualityProcedureRepository,
    QualityProcedurePaginationParams,
    QualityProcedurePaginatedResult,
    QualityProcedureFilter,
};
