//! Repository trait for NonConformance aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the NonConformance aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{NonConformance, NonConformanceSeverity, NonConformanceStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct NonConformancePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl NonConformancePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct NonConformancePaginatedResult {
    pub data: Vec<NonConformance>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct NonConformanceFilter {
    pub company_id: Option<Uuid>,
    pub subject: Option<String>,
    pub source_inspection_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub severity: Option<NonConformanceSeverity>,
    pub status: Option<NonConformanceStatus>,
    pub description: Option<String>,
}

impl NonConformanceFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.subject.is_some() || self.source_inspection_id.is_some() || self.item_id.is_some() || self.severity.is_some() || self.status.is_some() || self.description.is_some()
    }
}

/// Repository trait for NonConformance aggregate
///
/// This trait defines the persistence contract for NonConformance entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait NonConformanceRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new non_conformance entity
    async fn save(&self, entity: &NonConformance) -> Result<NonConformance>;

    /// Find non_conformance by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<NonConformance>>;

    /// Find all non_conformance entities
    async fn find_all(&self) -> Result<Vec<NonConformance>>;

    /// Update non_conformance by ID
    async fn update(&self, id: &str, entity: &NonConformance) -> Result<Option<NonConformance>>;

    /// Delete non_conformance by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List non_conformance with pagination
    async fn list(&self, params: NonConformancePaginationParams) -> Result<NonConformancePaginatedResult>;

    /// List non_conformance with pagination and filters
    async fn list_with_filters(&self, params: NonConformancePaginationParams, filters: NonConformanceFilter) -> Result<NonConformancePaginatedResult>;

    /// Count all non_conformance entities
    async fn count(&self) -> Result<u64>;

    /// Count non_conformance entities matching filters
    async fn count_with_filters(&self, filters: NonConformanceFilter) -> Result<u64>;

    /// Check if non_conformance exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete non_conformance by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted non_conformance by ID
    async fn restore(&self, id: &str) -> Result<Option<NonConformance>>;

    /// List soft-deleted non_conformance entities
    async fn list_deleted(&self, params: NonConformancePaginationParams) -> Result<NonConformancePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save non_conformance entities
    async fn bulk_save(&self, entities: &[NonConformance]) -> Result<Vec<NonConformance>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
