//! Repository trait for QualityInspectionTemplate aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the QualityInspectionTemplate aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::QualityInspectionTemplate;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QualityInspectionTemplatePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl QualityInspectionTemplatePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct QualityInspectionTemplatePaginatedResult {
    pub data: Vec<QualityInspectionTemplate>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QualityInspectionTemplateFilter {
    pub company_id: Option<Uuid>,
    pub template_name: Option<String>,
    pub item_id: Option<Uuid>,
    pub is_active: Option<bool>,
}

impl QualityInspectionTemplateFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.template_name.is_some() || self.item_id.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for QualityInspectionTemplate aggregate
///
/// This trait defines the persistence contract for QualityInspectionTemplate entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait QualityInspectionTemplateRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new quality_inspection_template entity
    async fn save(&self, entity: &QualityInspectionTemplate) -> Result<QualityInspectionTemplate>;

    /// Find quality_inspection_template by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<QualityInspectionTemplate>>;

    /// Find all quality_inspection_template entities
    async fn find_all(&self) -> Result<Vec<QualityInspectionTemplate>>;

    /// Update quality_inspection_template by ID
    async fn update(&self, id: &str, entity: &QualityInspectionTemplate) -> Result<Option<QualityInspectionTemplate>>;

    /// Delete quality_inspection_template by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List quality_inspection_template with pagination
    async fn list(&self, params: QualityInspectionTemplatePaginationParams) -> Result<QualityInspectionTemplatePaginatedResult>;

    /// List quality_inspection_template with pagination and filters
    async fn list_with_filters(&self, params: QualityInspectionTemplatePaginationParams, filters: QualityInspectionTemplateFilter) -> Result<QualityInspectionTemplatePaginatedResult>;

    /// Count all quality_inspection_template entities
    async fn count(&self) -> Result<u64>;

    /// Count quality_inspection_template entities matching filters
    async fn count_with_filters(&self, filters: QualityInspectionTemplateFilter) -> Result<u64>;

    /// Check if quality_inspection_template exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete quality_inspection_template by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted quality_inspection_template by ID
    async fn restore(&self, id: &str) -> Result<Option<QualityInspectionTemplate>>;

    /// List soft-deleted quality_inspection_template entities
    async fn list_deleted(&self, params: QualityInspectionTemplatePaginationParams) -> Result<QualityInspectionTemplatePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save quality_inspection_template entities
    async fn bulk_save(&self, entities: &[QualityInspectionTemplate]) -> Result<Vec<QualityInspectionTemplate>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
