//! Repository trait for QualityAction aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the QualityAction aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{QualityAction, QualityActionStatus, QualityActionType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QualityActionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl QualityActionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct QualityActionPaginatedResult {
    pub data: Vec<QualityAction>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QualityActionFilter {
    pub company_id: Option<Uuid>,
    pub non_conformance_id: Option<Uuid>,
    pub action_type: Option<QualityActionType>,
    pub procedure_id: Option<Uuid>,
    pub status: Option<QualityActionStatus>,
    pub description: Option<String>,
}

impl QualityActionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.non_conformance_id.is_some() || self.action_type.is_some() || self.procedure_id.is_some() || self.status.is_some() || self.description.is_some()
    }
}

/// Repository trait for QualityAction aggregate
///
/// This trait defines the persistence contract for QualityAction entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait QualityActionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new quality_action entity
    async fn save(&self, entity: &QualityAction) -> Result<QualityAction>;

    /// Find quality_action by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<QualityAction>>;

    /// Find all quality_action entities
    async fn find_all(&self) -> Result<Vec<QualityAction>>;

    /// Update quality_action by ID
    async fn update(&self, id: &str, entity: &QualityAction) -> Result<Option<QualityAction>>;

    /// Delete quality_action by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List quality_action with pagination
    async fn list(&self, params: QualityActionPaginationParams) -> Result<QualityActionPaginatedResult>;

    /// List quality_action with pagination and filters
    async fn list_with_filters(&self, params: QualityActionPaginationParams, filters: QualityActionFilter) -> Result<QualityActionPaginatedResult>;

    /// Count all quality_action entities
    async fn count(&self) -> Result<u64>;

    /// Count quality_action entities matching filters
    async fn count_with_filters(&self, filters: QualityActionFilter) -> Result<u64>;

    /// Check if quality_action exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete quality_action by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted quality_action by ID
    async fn restore(&self, id: &str) -> Result<Option<QualityAction>>;

    /// List soft-deleted quality_action entities
    async fn list_deleted(&self, params: QualityActionPaginationParams) -> Result<QualityActionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save quality_action entities
    async fn bulk_save(&self, entities: &[QualityAction]) -> Result<Vec<QualityAction>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
