//! Repository trait for QualityInspectionParameter aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the QualityInspectionParameter aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::QualityInspectionParameter;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QualityInspectionParameterPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl QualityInspectionParameterPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct QualityInspectionParameterPaginatedResult {
    pub data: Vec<QualityInspectionParameter>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QualityInspectionParameterFilter {
    pub template_id: Option<Uuid>,
    pub parameter_name: Option<String>,
    pub numeric: Option<bool>,
    pub spec_text: Option<String>,
}

impl QualityInspectionParameterFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.template_id.is_some() || self.parameter_name.is_some() || self.numeric.is_some() || self.spec_text.is_some()
    }
}

/// Repository trait for QualityInspectionParameter aggregate
///
/// This trait defines the persistence contract for QualityInspectionParameter entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait QualityInspectionParameterRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new quality_inspection_parameter entity
    async fn save(&self, entity: &QualityInspectionParameter) -> Result<QualityInspectionParameter>;

    /// Find quality_inspection_parameter by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<QualityInspectionParameter>>;

    /// Find all quality_inspection_parameter entities
    async fn find_all(&self) -> Result<Vec<QualityInspectionParameter>>;

    /// Update quality_inspection_parameter by ID
    async fn update(&self, id: &str, entity: &QualityInspectionParameter) -> Result<Option<QualityInspectionParameter>>;

    /// Delete quality_inspection_parameter by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List quality_inspection_parameter with pagination
    async fn list(&self, params: QualityInspectionParameterPaginationParams) -> Result<QualityInspectionParameterPaginatedResult>;

    /// List quality_inspection_parameter with pagination and filters
    async fn list_with_filters(&self, params: QualityInspectionParameterPaginationParams, filters: QualityInspectionParameterFilter) -> Result<QualityInspectionParameterPaginatedResult>;

    /// Count all quality_inspection_parameter entities
    async fn count(&self) -> Result<u64>;

    /// Count quality_inspection_parameter entities matching filters
    async fn count_with_filters(&self, filters: QualityInspectionParameterFilter) -> Result<u64>;

    /// Check if quality_inspection_parameter exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete quality_inspection_parameter by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted quality_inspection_parameter by ID
    async fn restore(&self, id: &str) -> Result<Option<QualityInspectionParameter>>;

    /// List soft-deleted quality_inspection_parameter entities
    async fn list_deleted(&self, params: QualityInspectionParameterPaginationParams) -> Result<QualityInspectionParameterPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save quality_inspection_parameter entities
    async fn bulk_save(&self, entities: &[QualityInspectionParameter]) -> Result<Vec<QualityInspectionParameter>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
