//! Repository trait for QualityProcedure aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the QualityProcedure aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::QualityProcedure;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QualityProcedurePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl QualityProcedurePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct QualityProcedurePaginatedResult {
    pub data: Vec<QualityProcedure>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QualityProcedureFilter {
    pub company_id: Option<Uuid>,
    pub procedure_name: Option<String>,
    pub parent_procedure_id: Option<Uuid>,
    pub description: Option<String>,
    pub is_active: Option<bool>,
}

impl QualityProcedureFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.procedure_name.is_some() || self.parent_procedure_id.is_some() || self.description.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for QualityProcedure aggregate
///
/// This trait defines the persistence contract for QualityProcedure entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait QualityProcedureRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new quality_procedure entity
    async fn save(&self, entity: &QualityProcedure) -> Result<QualityProcedure>;

    /// Find quality_procedure by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<QualityProcedure>>;

    /// Find all quality_procedure entities
    async fn find_all(&self) -> Result<Vec<QualityProcedure>>;

    /// Update quality_procedure by ID
    async fn update(&self, id: &str, entity: &QualityProcedure) -> Result<Option<QualityProcedure>>;

    /// Delete quality_procedure by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List quality_procedure with pagination
    async fn list(&self, params: QualityProcedurePaginationParams) -> Result<QualityProcedurePaginatedResult>;

    /// List quality_procedure with pagination and filters
    async fn list_with_filters(&self, params: QualityProcedurePaginationParams, filters: QualityProcedureFilter) -> Result<QualityProcedurePaginatedResult>;

    /// Count all quality_procedure entities
    async fn count(&self) -> Result<u64>;

    /// Count quality_procedure entities matching filters
    async fn count_with_filters(&self, filters: QualityProcedureFilter) -> Result<u64>;

    /// Check if quality_procedure exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete quality_procedure by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted quality_procedure by ID
    async fn restore(&self, id: &str) -> Result<Option<QualityProcedure>>;

    /// List soft-deleted quality_procedure entities
    async fn list_deleted(&self, params: QualityProcedurePaginationParams) -> Result<QualityProcedurePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save quality_procedure entities
    async fn bulk_save(&self, entities: &[QualityProcedure]) -> Result<Vec<QualityProcedure>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
