//! Repository trait for QualityInspection aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the QualityInspection aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{QualityInspection, InspectionStatus, InspectionType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QualityInspectionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl QualityInspectionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct QualityInspectionPaginatedResult {
    pub data: Vec<QualityInspection>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QualityInspectionFilter {
    pub company_id: Option<Uuid>,
    pub template_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub inspection_type: Option<InspectionType>,
    pub source_type: Option<String>,
    pub source_id: Option<Uuid>,
    pub status: Option<InspectionStatus>,
    pub remarks: Option<String>,
}

impl QualityInspectionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.template_id.is_some() || self.item_id.is_some() || self.inspection_type.is_some() || self.source_type.is_some() || self.source_id.is_some() || self.status.is_some() || self.remarks.is_some()
    }
}

/// Repository trait for QualityInspection aggregate
///
/// This trait defines the persistence contract for QualityInspection entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait QualityInspectionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new quality_inspection entity
    async fn save(&self, entity: &QualityInspection) -> Result<QualityInspection>;

    /// Find quality_inspection by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<QualityInspection>>;

    /// Find all quality_inspection entities
    async fn find_all(&self) -> Result<Vec<QualityInspection>>;

    /// Update quality_inspection by ID
    async fn update(&self, id: &str, entity: &QualityInspection) -> Result<Option<QualityInspection>>;

    /// Delete quality_inspection by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List quality_inspection with pagination
    async fn list(&self, params: QualityInspectionPaginationParams) -> Result<QualityInspectionPaginatedResult>;

    /// List quality_inspection with pagination and filters
    async fn list_with_filters(&self, params: QualityInspectionPaginationParams, filters: QualityInspectionFilter) -> Result<QualityInspectionPaginatedResult>;

    /// Count all quality_inspection entities
    async fn count(&self) -> Result<u64>;

    /// Count quality_inspection entities matching filters
    async fn count_with_filters(&self, filters: QualityInspectionFilter) -> Result<u64>;

    /// Check if quality_inspection exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete quality_inspection by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted quality_inspection by ID
    async fn restore(&self, id: &str) -> Result<Option<QualityInspection>>;

    /// List soft-deleted quality_inspection entities
    async fn list_deleted(&self, params: QualityInspectionPaginationParams) -> Result<QualityInspectionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save quality_inspection entities
    async fn bulk_save(&self, entities: &[QualityInspection]) -> Result<Vec<QualityInspection>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
