//! Repository trait for QualityInspectionReading aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the QualityInspectionReading aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{QualityInspectionReading, ReadingResult};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QualityInspectionReadingPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl QualityInspectionReadingPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct QualityInspectionReadingPaginatedResult {
    pub data: Vec<QualityInspectionReading>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QualityInspectionReadingFilter {
    pub company_id: Option<Uuid>,
    pub inspection_id: Option<Uuid>,
    pub parameter_name: Option<String>,
    pub numeric: Option<bool>,
    pub manual_result: Option<bool>,
    pub result: Option<ReadingResult>,
    pub remarks: Option<String>,
}

impl QualityInspectionReadingFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.inspection_id.is_some() || self.parameter_name.is_some() || self.numeric.is_some() || self.manual_result.is_some() || self.result.is_some() || self.remarks.is_some()
    }
}

/// Repository trait for QualityInspectionReading aggregate
///
/// This trait defines the persistence contract for QualityInspectionReading entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait QualityInspectionReadingRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new quality_inspection_reading entity
    async fn save(&self, entity: &QualityInspectionReading) -> Result<QualityInspectionReading>;

    /// Find quality_inspection_reading by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<QualityInspectionReading>>;

    /// Find all quality_inspection_reading entities
    async fn find_all(&self) -> Result<Vec<QualityInspectionReading>>;

    /// Update quality_inspection_reading by ID
    async fn update(&self, id: &str, entity: &QualityInspectionReading) -> Result<Option<QualityInspectionReading>>;

    /// Delete quality_inspection_reading by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List quality_inspection_reading with pagination
    async fn list(&self, params: QualityInspectionReadingPaginationParams) -> Result<QualityInspectionReadingPaginatedResult>;

    /// List quality_inspection_reading with pagination and filters
    async fn list_with_filters(&self, params: QualityInspectionReadingPaginationParams, filters: QualityInspectionReadingFilter) -> Result<QualityInspectionReadingPaginatedResult>;

    /// Count all quality_inspection_reading entities
    async fn count(&self) -> Result<u64>;

    /// Count quality_inspection_reading entities matching filters
    async fn count_with_filters(&self, filters: QualityInspectionReadingFilter) -> Result<u64>;

    /// Check if quality_inspection_reading exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete quality_inspection_reading by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted quality_inspection_reading by ID
    async fn restore(&self, id: &str) -> Result<Option<QualityInspectionReading>>;

    /// List soft-deleted quality_inspection_reading entities
    async fn list_deleted(&self, params: QualityInspectionReadingPaginationParams) -> Result<QualityInspectionReadingPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save quality_inspection_reading entities
    async fn bulk_save(&self, entities: &[QualityInspectionReading]) -> Result<Vec<QualityInspectionReading>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
