//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod non_conformance_repository;
mod quality_action_repository;
mod quality_inspection_repository;
mod quality_inspection_reading_repository;
mod quality_inspection_template_repository;
mod quality_inspection_parameter_repository;
mod quality_procedure_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use non_conformance_repository::NonConformanceRepository;
pub use quality_action_repository::QualityActionRepository;
pub use quality_inspection_repository::QualityInspectionRepository;
pub use quality_inspection_reading_repository::QualityInspectionReadingRepository;
pub use quality_inspection_template_repository::QualityInspectionTemplateRepository;
pub use quality_inspection_parameter_repository::QualityInspectionParameterRepository;
pub use quality_procedure_repository::QualityProcedureRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
