//! Repository for NonConformance entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written NonConformance SQL (4-layer rule: services orchestrate and own the unit of work,
//! repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<NonConformance, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use chrono::{DateTime, Utc};
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::NonConformance;

/// Table name for NonConformance entities
pub const TABLE_NAME: &str = "quality.non_conformances";

/// Repository for NonConformance entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct NonConformanceRepository(
    backbone_orm::GenericCrudRepository<NonConformance, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for NonConformanceRepository {
    type Target = backbone_orm::GenericCrudRepository<NonConformance, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl NonConformanceRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a raised non-conformance writes.
///
/// Mirrors the raw column shape rather than the `NonConformance` entity: `severity` is carried as a free
/// string and cast at the DB (`$6::non_conformance_severity`), so a bad severity fails as a DB error
/// rather than a deserialize panic.
pub struct NewNonConformanceRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub subject: &'a str,
    pub source_inspection_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub severity: &'a str,
    pub description: Option<&'a str>,
    pub opened_at: DateTime<Utc>,
}

/// The locked NC projection the close decision needs: its company (only knowable AFTER the read) and its
/// live status.
pub struct LockedNonConformanceRow {
    pub company_id: Uuid,
    pub status: String,
}

/// Hand-written NonConformance SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl NonConformanceRepository {
    /// Raise a non-conformance.
    ///
    /// A write outside any transaction: takes the pool and runs `execute_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))` — the company is
    /// on the DTO, and that scope is what satisfies the INSERT's WITH CHECK fence.
    pub async fn insert_non_conformance(
        &self,
        pool: &PgPool,
        nc: &NewNonConformanceRow<'_>,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO quality.non_conformances
                     (id, company_id, subject, source_inspection_id, item_id, severity, status, description, opened_at)
                   VALUES ($1,$2,$3,$4,$5,$6::non_conformance_severity,'open'::non_conformance_status,$7,$8)"#,
            )
            .bind(nc.id).bind(nc.company_id).bind(nc.subject).bind(nc.source_inspection_id).bind(nc.item_id)
            .bind(nc.severity).bind(nc.description).bind(nc.opened_at),
        )
        .await?;
        Ok(())
    }

    /// Lock the NC row and read its company + status — the gate a concurrent close must serialize
    /// against, and the company a CAPA action's cited procedure is validated against (ADR-0010 F2).
    ///
    /// Takes the CALLER'S connection: the lock must be held across the action insert that follows. The
    /// caller has already bound the scope on that connection — don't re-bind here.
    pub async fn lock_status(
        &self,
        conn: &mut sqlx::PgConnection,
        nc_id: Uuid,
    ) -> Result<Option<LockedNonConformanceRow>, sqlx::Error> {
        let row = sqlx::query(
            r#"SELECT company_id, status::text AS status FROM quality.non_conformances
               WHERE id=$1 AND (metadata->>'deleted_at') IS NULL FOR UPDATE"#,
        )
        .bind(nc_id)
        .fetch_optional(conn)
        .await?;
        Ok(row.map(|r| LockedNonConformanceRow { company_id: r.get("company_id"), status: r.get("status") }))
    }

    /// Lock the NC row and read the company + status the close decision needs. The company is only
    /// knowable AFTER this read, which is why the caller cannot bind it up front.
    ///
    /// Takes the CALLER'S connection: the lock must be held across the completeness check and the close.
    pub async fn lock_for_close(
        &self,
        conn: &mut sqlx::PgConnection,
        nc_id: Uuid,
    ) -> Result<Option<LockedNonConformanceRow>, sqlx::Error> {
        let row = sqlx::query(
            r#"SELECT company_id, status::text AS status FROM quality.non_conformances
               WHERE id=$1 AND (metadata->>'deleted_at') IS NULL FOR UPDATE"#,
        )
        .bind(nc_id)
        .fetch_optional(conn)
        .await?;
        Ok(row.map(|r| LockedNonConformanceRow { company_id: r.get("company_id"), status: r.get("status") }))
    }

    /// Advance an open NC to in_progress (the status filter makes it a no-op once it already is).
    ///
    /// Takes the CALLER'S connection — it must be the one holding the `lock_status` lock, so the action
    /// insert and this advance commit together.
    pub async fn mark_in_progress(&self, conn: &mut sqlx::PgConnection, nc_id: Uuid) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"UPDATE quality.non_conformances SET status='in_progress'::non_conformance_status
               WHERE id=$1 AND status='open'::non_conformance_status"#,
        )
        .bind(nc_id)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Close the NC. Takes the CALLER'S connection — it must be the one holding the `lock_for_close`
    /// lock, which is what serializes a concurrent `add_quality_action` against this close.
    pub async fn close(
        &self,
        conn: &mut sqlx::PgConnection,
        nc_id: Uuid,
        now: DateTime<Utc>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"UPDATE quality.non_conformances SET status='closed'::non_conformance_status, closed_at=$2
               WHERE id=$1"#,
        )
        .bind(nc_id).bind(now)
        .execute(conn)
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(NonConformanceRepository, NonConformance, soft_delete);
