//! Repository for QualityInspectionTemplate entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written QualityInspectionTemplate SQL (4-layer rule: services orchestrate and own the unit of work,
//! repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<QualityInspectionTemplate, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::entity::QualityInspectionTemplate;

/// Table name for QualityInspectionTemplate entities
pub const TABLE_NAME: &str = "quality.quality_inspection_templates";

/// Repository for QualityInspectionTemplate entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct QualityInspectionTemplateRepository(
    backbone_orm::GenericCrudRepository<QualityInspectionTemplate, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for QualityInspectionTemplateRepository {
    type Target = backbone_orm::GenericCrudRepository<QualityInspectionTemplate, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl QualityInspectionTemplateRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row an inspection template writes.
///
/// Mirrors the raw column shape rather than the `QualityInspectionTemplate` entity.
pub struct NewTemplateRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub template_name: &'a str,
    pub item_id: Option<Uuid>,
}

/// Hand-written QualityInspectionTemplate SQL. Lives here (not in the write service) per the module's
/// 4-layer rule.
impl QualityInspectionTemplateRepository {
    /// Insert the template header. Takes the CALLER'S connection so the header and its parameter rows
    /// commit as one unit. The caller binds the company on that connection (`bind_company_on`) before
    /// calling — don't re-bind here.
    pub async fn insert_template(
        &self,
        conn: &mut sqlx::PgConnection,
        t: &NewTemplateRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO quality.quality_inspection_templates (id, company_id, template_name, item_id, is_active)
               VALUES ($1,$2,$3,$4,true)"#,
        )
        .bind(t.id).bind(t.company_id).bind(t.template_name).bind(t.item_id)
        .execute(conn)
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(QualityInspectionTemplateRepository, QualityInspectionTemplate, soft_delete);
