//! Repository for QualityProcedure entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written QualityProcedure SQL (4-layer rule: services orchestrate and own the unit of work,
//! repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<QualityProcedure, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::QualityProcedure;

/// Table name for QualityProcedure entities
pub const TABLE_NAME: &str = "quality.quality_procedures";

/// Repository for QualityProcedure entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct QualityProcedureRepository(
    backbone_orm::GenericCrudRepository<QualityProcedure, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for QualityProcedureRepository {
    type Target = backbone_orm::GenericCrudRepository<QualityProcedure, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl QualityProcedureRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a quality procedure writes.
///
/// Mirrors the raw column shape rather than the `QualityProcedure` entity.
pub struct NewProcedureRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub procedure_name: &'a str,
    pub parent_procedure_id: Option<Uuid>,
    pub description: Option<&'a str>,
}

/// Hand-written QualityProcedure SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl QualityProcedureRepository {
    /// Probe that a parent procedure exists in this company — the adjacency-list tree must not cross a
    /// tenant boundary.
    ///
    /// A read outside any transaction: takes the pool and runs `fetch_optional_scalar_scoped` so the RLS
    /// fence (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))`. The
    /// explicit `company_id = $2` filter stays as defense-in-depth.
    pub async fn find_id_in_company(
        &self,
        pool: &PgPool,
        procedure_id: Uuid,
        company_id: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar("SELECT id FROM quality.quality_procedures WHERE id=$1 AND company_id=$2")
                .bind(procedure_id).bind(company_id),
        )
        .await
    }

    /// Insert a procedure.
    ///
    /// A write outside any transaction: takes the pool and runs `execute_scoped` so the RLS fence
    /// applies. The caller wraps this in `with_company_scope(Some(company))` — the company is on the
    /// DTO, and that scope is what satisfies the INSERT's WITH CHECK fence.
    pub async fn insert_procedure(&self, pool: &PgPool, p: &NewProcedureRow<'_>) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO quality.quality_procedures
                     (id, company_id, procedure_name, parent_procedure_id, description, is_active)
                   VALUES ($1,$2,$3,$4,$5,true)"#,
            )
            .bind(p.id).bind(p.company_id).bind(p.procedure_name).bind(p.parent_procedure_id).bind(p.description),
        )
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(QualityProcedureRepository, QualityProcedure, soft_delete);
