//! Repository for QualityInspectionReading entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<QualityInspectionReading, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::QualityInspectionReading;

/// Table name for QualityInspectionReading entities
pub const TABLE_NAME: &str = "quality.quality_inspection_readings";

/// Repository for QualityInspectionReading entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct QualityInspectionReadingRepository(
    backbone_orm::GenericCrudRepository<QualityInspectionReading, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for QualityInspectionReadingRepository {
    type Target = backbone_orm::GenericCrudRepository<QualityInspectionReading, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl QualityInspectionReadingRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(QualityInspectionReadingRepository, QualityInspectionReading, soft_delete);
