//! Repository for QualityInspectionParameter entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written QualityInspectionParameter SQL (4-layer rule: services orchestrate and own the unit of work,
//! repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<QualityInspectionParameter, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::QualityInspectionParameter;

/// Table name for QualityInspectionParameter entities
pub const TABLE_NAME: &str = "quality.quality_inspection_parameters";

/// Repository for QualityInspectionParameter entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct QualityInspectionParameterRepository(
    backbone_orm::GenericCrudRepository<QualityInspectionParameter, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for QualityInspectionParameterRepository {
    type Target = backbone_orm::GenericCrudRepository<QualityInspectionParameter, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl QualityInspectionParameterRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a template parameter (its acceptance criterion) writes.
///
/// Mirrors the raw column shape rather than the `QualityInspectionParameter` entity.
pub struct NewTemplateParameterRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub template_id: Uuid,
    pub parameter_name: &'a str,
    pub numeric: bool,
    pub min_value: Option<Decimal>,
    pub max_value: Option<Decimal>,
    pub spec_text: Option<&'a str>,
}

/// One parameter's acceptance criterion, as the verdict reads it.
pub struct CriterionRow {
    pub parameter_name: String,
    pub numeric: bool,
    pub min_value: Option<Decimal>,
    pub max_value: Option<Decimal>,
}

/// Hand-written QualityInspectionParameter SQL. Lives here (not in the write service) per the module's
/// 4-layer rule.
impl QualityInspectionParameterRepository {
    /// Insert one parameter + its criterion. Takes the CALLER'S connection so it commits with the
    /// template header it belongs to. The caller has already bound the company on this connection —
    /// don't re-bind here. `company_id` is the DENORMALIZED owner (ADR-0010 Decision A): copied from
    /// the template header by the write path so the FORALL RLS fence applies without a parent-join.
    /// The WITH CHECK policy verifies it matches the ambient `app.company_id` (which the caller has
    /// bound).
    pub async fn insert_parameter(
        &self,
        conn: &mut sqlx::PgConnection,
        p: &NewTemplateParameterRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO quality.quality_inspection_parameters
                 (id, company_id, template_id, parameter_name, numeric, min_value, max_value, spec_text)
               VALUES ($1,$2,$3,$4,$5,$6,$7,$8)"#,
        )
        .bind(p.id).bind(p.company_id).bind(p.template_id).bind(p.parameter_name).bind(p.numeric)
        .bind(p.min_value).bind(p.max_value).bind(p.spec_text)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// The WHOLE template's criteria in one snapshot — consistent across readings, and the basis for the
    /// caller's coverage check.
    ///
    /// A read outside any transaction: takes the pool and runs `fetch_all_rows_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))`, so a template
    /// belonging to another tenant reads as absent rather than leaking its criteria.
    pub async fn list_criteria(&self, pool: &PgPool, template_id: Uuid) -> Result<Vec<CriterionRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"SELECT parameter_name, numeric, min_value, max_value FROM quality.quality_inspection_parameters
                   WHERE template_id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(template_id),
        )
        .await?;
        Ok(rows
            .iter()
            .map(|p| CriterionRow {
                parameter_name: p.get("parameter_name"),
                numeric: p.get("numeric"),
                min_value: p.get("min_value"),
                max_value: p.get("max_value"),
            })
            .collect())
    }
}

backbone_core::impl_crud_repository!(QualityInspectionParameterRepository, QualityInspectionParameter, soft_delete);
