//! Repository for QualityInspectionReading entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written QualityInspectionReading SQL (4-layer rule: services orchestrate and own the unit of work,
//! repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<QualityInspectionReading, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::entity::QualityInspectionReading;

/// Table name for QualityInspectionReading entities
pub const TABLE_NAME: &str = "quality.quality_inspection_readings";

/// Repository for QualityInspectionReading entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct QualityInspectionReadingRepository(
    backbone_orm::GenericCrudRepository<QualityInspectionReading, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for QualityInspectionReadingRepository {
    type Target = backbone_orm::GenericCrudRepository<QualityInspectionReading, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl QualityInspectionReadingRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row one judged reading writes.
///
/// Mirrors the raw column shape rather than the `QualityInspectionReading` entity. The criterion
/// (`min_value`/`max_value`) is SNAPSHOTTED onto the reading, and `result` is the caller's already-made
/// per-reading judgement, cast at the DB (`$9::reading_result`) — the SQL does not re-judge it.
pub struct NewReadingRow<'a> {
    pub id: Uuid,
    pub inspection_id: Uuid,
    pub parameter_name: &'a str,
    pub numeric: bool,
    pub reading_value: Option<Decimal>,
    pub min_value: Option<Decimal>,
    pub max_value: Option<Decimal>,
    pub manual_result: Option<bool>,
    pub result: &'a str,
    pub remarks: Option<&'a str>,
}

/// Hand-written QualityInspectionReading SQL. Lives here (not in the write service) per the module's
/// 4-layer rule.
impl QualityInspectionReadingRepository {
    /// Insert one judged reading. Takes the CALLER'S connection so it commits with the inspection header
    /// it belongs to. The caller has already bound the company — don't re-bind here.
    pub async fn insert_reading(
        &self,
        conn: &mut sqlx::PgConnection,
        r: &NewReadingRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO quality.quality_inspection_readings
                 (id, inspection_id, parameter_name, numeric, reading_value, min_value, max_value,
                  manual_result, result, remarks)
               VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::reading_result,$10)"#,
        )
        .bind(r.id).bind(r.inspection_id).bind(r.parameter_name).bind(r.numeric).bind(r.reading_value)
        .bind(r.min_value).bind(r.max_value).bind(r.manual_result).bind(r.result).bind(r.remarks)
        .execute(conn)
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(QualityInspectionReadingRepository, QualityInspectionReading, soft_delete);
