//! Repository for QualityAction entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<QualityAction, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::QualityAction;

/// Table name for QualityAction entities
pub const TABLE_NAME: &str = "quality.quality_actions";

/// Repository for QualityAction entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct QualityActionRepository(
    backbone_orm::GenericCrudRepository<QualityAction, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for QualityActionRepository {
    type Target = backbone_orm::GenericCrudRepository<QualityAction, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl QualityActionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(QualityActionRepository, QualityAction, soft_delete);
