//! Repository for QualityInspectionTemplate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<QualityInspectionTemplate, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::QualityInspectionTemplate;

/// Table name for QualityInspectionTemplate entities
pub const TABLE_NAME: &str = "quality.quality_inspection_templates";

/// Repository for QualityInspectionTemplate entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct QualityInspectionTemplateRepository(
    backbone_orm::GenericCrudRepository<QualityInspectionTemplate, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for QualityInspectionTemplateRepository {
    type Target = backbone_orm::GenericCrudRepository<QualityInspectionTemplate, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl QualityInspectionTemplateRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(QualityInspectionTemplateRepository, QualityInspectionTemplate, soft_delete);
