//! Repository for QualityProcedure entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written QualityProcedure SQL (4-layer rule: services orchestrate and own the unit of work,
//! repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<QualityProcedure, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.
//!
//! The module carries no tenancy of its own (ADR-0029): statements are tenant-agnostic and ride the
//! composing service's ambient org scope.

use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::org_scope;
// The scalar read twin lives only in the legacy `company_scope` module. Its connection
// discipline is what this repository needs — request-dedicated connection when the composing
// service bound one, plain pool otherwise. The helper's legacy task-local branch is never
// taken: this module sets no legacy scope of its own (ADR-0029).
use backbone_orm::company_scope::fetch_optional_scalar_scoped;

use crate::domain::entity::QualityProcedure;

/// Table name for QualityProcedure entities
pub const TABLE_NAME: &str = "quality.quality_procedures";

/// Repository for QualityProcedure entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct QualityProcedureRepository(
    backbone_orm::GenericCrudRepository<QualityProcedure, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for QualityProcedureRepository {
    type Target = backbone_orm::GenericCrudRepository<QualityProcedure, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl QualityProcedureRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a quality procedure writes.
///
/// Mirrors the raw column shape rather than the `QualityProcedure` entity.
pub struct NewProcedureRow<'a> {
    pub id: Uuid,
    pub procedure_name: &'a str,
    pub parent_procedure_id: Option<Uuid>,
    pub description: Option<&'a str>,
}

/// Hand-written QualityProcedure SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl QualityProcedureRepository {
    /// Probe that a procedure id exists — a parent (or a CAPA-cited) procedure must be visible to the
    /// caller. ID-only: no tenant argument; under a composed tenancy decorator a foreign tenant's
    /// procedure reads as absent.
    ///
    /// A read outside any transaction: takes the pool and runs the scoped read helper, so once the
    /// decorator is installed the probe rides the request-dedicated connection.
    pub async fn find_id(&self, pool: &PgPool, procedure_id: Uuid) -> Result<Option<Uuid>, sqlx::Error> {
        fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar("SELECT id FROM quality.quality_procedures WHERE id=$1")
                .bind(procedure_id),
        )
        .await
    }

    /// Insert a procedure.
    ///
    /// A write outside any transaction: takes the pool and runs `execute_scoped` — under a composer's
    /// request scope it rides the request-dedicated connection; with no scope bound it is a plain
    /// unfenced execute (ADR-0029).
    pub async fn insert_procedure(&self, pool: &PgPool, p: &NewProcedureRow<'_>) -> Result<(), sqlx::Error> {
        org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO quality.quality_procedures
                     (id, procedure_name, parent_procedure_id, description, status)
                   VALUES ($1,$2,$3,$4,'active')"#,
            )
            .bind(p.id).bind(p.procedure_name).bind(p.parent_procedure_id).bind(p.description),
        )
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(QualityProcedureRepository, QualityProcedure, soft_delete);
