//! Repository for QualityAction entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written QualityAction SQL (4-layer rule: services orchestrate and own the unit of work,
//! repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<QualityAction, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.
//!
//! The module carries no tenancy of its own (ADR-0029): statements are tenant-agnostic and ride the
//! composing service's ambient org scope.

use chrono::{DateTime, Utc};
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::org_scope;
// The scalar read twin lives only in the legacy `company_scope` module. Its connection
// discipline is what this repository needs — request-dedicated connection when the composing
// service bound one, plain pool otherwise. The helper's legacy task-local branch is never
// taken: this module sets no legacy scope of its own (ADR-0029).
use backbone_orm::company_scope::fetch_optional_scalar_scoped;

use crate::domain::entity::QualityAction;

/// Table name for QualityAction entities
pub const TABLE_NAME: &str = "quality.quality_actions";

/// Repository for QualityAction entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct QualityActionRepository(
    backbone_orm::GenericCrudRepository<QualityAction, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for QualityActionRepository {
    type Target = backbone_orm::GenericCrudRepository<QualityAction, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl QualityActionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a CAPA action writes.
///
/// Mirrors the raw column shape rather than the `QualityAction` entity: `action_type` is carried as a
/// free string and cast at the DB (`$3::quality_action_type`).
pub struct NewQualityActionRow<'a> {
    pub id: Uuid,
    pub non_conformance_id: Uuid,
    pub action_type: &'a str,
    pub procedure_id: Option<Uuid>,
    pub description: &'a str,
    pub due_date: Option<DateTime<Utc>>,
}

/// Hand-written QualityAction SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl QualityActionRepository {
    /// Insert a CAPA action.
    ///
    /// Takes the CALLER'S connection: this must run under the `FOR UPDATE` lock the caller holds on the
    /// NC row, so a concurrent close can't slip a fresh action past it. The caller has already relayed
    /// the ambient org scope onto that connection — don't re-bind here.
    pub async fn insert_action(
        &self,
        conn: &mut sqlx::PgConnection,
        a: &NewQualityActionRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO quality.quality_actions
                 (id, non_conformance_id, action_type, procedure_id, status, description, due_date)
               VALUES ($1,$2,$3::quality_action_type,$4,'open'::quality_action_status,$5,$6)"#,
        )
        .bind(a.id).bind(a.non_conformance_id).bind(a.action_type).bind(a.procedure_id)
        .bind(a.description).bind(a.due_date)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Mark an action completed (terminal). Returns rows affected (0 = already completed, or not found —
    /// the caller disambiguates with `exists`).
    ///
    /// ID-only: no tenant argument. Runs `execute_scoped`, so it rides the request-dedicated connection
    /// when the composing service bound one and another tenant's action simply is not updated; with no
    /// scope bound it is a plain unfenced execute (ADR-0029).
    pub async fn complete(
        &self,
        pool: &PgPool,
        action_id: Uuid,
        now: DateTime<Utc>,
    ) -> Result<u64, sqlx::Error> {
        let moved = org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE quality.quality_actions
                   SET status='completed'::quality_action_status, completed_at=$2
                   WHERE id=$1 AND status <> 'completed'::quality_action_status AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(action_id).bind(now),
        )
        .await?;
        Ok(moved.rows_affected())
    }

    /// Does this action exist in scope? Disambiguates "already completed" (an idempotent no-op) from
    /// "not found" after a 0-row `complete`. ID-only read, same request-scope discipline as `complete`.
    pub async fn exists(&self, pool: &PgPool, action_id: Uuid) -> Result<Option<Uuid>, sqlx::Error> {
        fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar("SELECT id FROM quality.quality_actions WHERE id=$1").bind(action_id),
        )
        .await
    }

    /// How many of this NC's actions are still outstanding — the close gate.
    ///
    /// Takes the CALLER'S connection: this must be read under the same `FOR UPDATE` lock (and the same
    /// snapshot) as the close it gates.
    pub async fn count_incomplete(
        &self,
        conn: &mut sqlx::PgConnection,
        nc_id: Uuid,
    ) -> Result<i64, sqlx::Error> {
        sqlx::query_scalar(
            r#"SELECT count(*) FROM quality.quality_actions
               WHERE non_conformance_id=$1 AND status <> 'completed'::quality_action_status"#,
        )
        .bind(nc_id)
        .fetch_one(conn)
        .await
    }
}

backbone_core::impl_crud_repository!(QualityActionRepository, QualityAction, soft_delete);
