//! Repository for QualityInspection entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<QualityInspection, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::QualityInspection;

/// Table name for QualityInspection entities
pub const TABLE_NAME: &str = "quality.quality_inspections";

/// Repository for QualityInspection entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct QualityInspectionRepository(
    backbone_orm::GenericCrudRepository<QualityInspection, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for QualityInspectionRepository {
    type Target = backbone_orm::GenericCrudRepository<QualityInspection, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl QualityInspectionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(QualityInspectionRepository, QualityInspection, soft_delete);
