//! Repository for QualityProcedure entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<QualityProcedure, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::QualityProcedure;

/// Table name for QualityProcedure entities
pub const TABLE_NAME: &str = "quality.quality_procedures";

/// Repository for QualityProcedure entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct QualityProcedureRepository(
    backbone_orm::GenericCrudRepository<QualityProcedure, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for QualityProcedureRepository {
    type Target = backbone_orm::GenericCrudRepository<QualityProcedure, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl QualityProcedureRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(QualityProcedureRepository, QualityProcedure, soft_delete);
