//! Repository for QualityInspectionParameter entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<QualityInspectionParameter, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::QualityInspectionParameter;

/// Table name for QualityInspectionParameter entities
pub const TABLE_NAME: &str = "quality.quality_inspection_parameters";

/// Repository for QualityInspectionParameter entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct QualityInspectionParameterRepository(
    backbone_orm::GenericCrudRepository<QualityInspectionParameter, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for QualityInspectionParameterRepository {
    type Target = backbone_orm::GenericCrudRepository<QualityInspectionParameter, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl QualityInspectionParameterRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(QualityInspectionParameterRepository, QualityInspectionParameter, soft_delete);
