//! Repository for QualityInspection entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written QualityInspection SQL (4-layer rule: services orchestrate and own the unit of work,
//! repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<QualityInspection, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.
//!
//! The module carries no tenancy of its own (ADR-0029): statements are tenant-agnostic and ride the
//! composing service's ambient org scope.

use chrono::{DateTime, Utc};
use sqlx::PgPool;
use uuid::Uuid;

// The scalar read twin lives only in the legacy `company_scope` module. Its connection
// discipline is what this repository needs — request-dedicated connection when the composing
// service bound one, plain pool otherwise. The helper's legacy task-local branch is never
// taken: this module sets no legacy scope of its own (ADR-0029).
use backbone_orm::company_scope::fetch_optional_scalar_scoped;

use crate::domain::entity::QualityInspection;

/// Table name for QualityInspection entities
pub const TABLE_NAME: &str = "quality.quality_inspections";

/// Repository for QualityInspection entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct QualityInspectionRepository(
    backbone_orm::GenericCrudRepository<QualityInspection, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for QualityInspectionRepository {
    type Target = backbone_orm::GenericCrudRepository<QualityInspection, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl QualityInspectionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a completed inspection writes.
///
/// Mirrors the raw column shape rather than the `QualityInspection` entity: `inspection_type` and
/// `status` are carried as free strings and cast at the DB (`$4::inspection_type`,
/// `$8::inspection_status`), so a bad value fails as a DB error rather than a deserialize panic. The
/// verdict (`status`) is already judged by the caller — the SQL does not decide it.
pub struct NewInspectionRow<'a> {
    pub id: Uuid,
    pub template_id: Uuid,
    pub item_id: Uuid,
    pub inspection_type: &'a str,
    pub source_type: Option<&'a str>,
    pub source_id: Option<Uuid>,
    pub sample_size: i32,
    pub inspected_at: DateTime<Utc>,
    pub status: &'a str,
}

/// Hand-written QualityInspection SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl QualityInspectionRepository {
    /// Insert the inspection header with its judged verdict.
    ///
    /// Takes the CALLER'S connection so the header, its readings, and the outbox stage commit as one
    /// unit — Stock subscribes to the disposition, so a crash between commit and the in-proc publish
    /// must not drop it. The caller has already relayed the ambient org scope onto that connection
    /// (`relay_ambient_scope`) — don't re-bind here.
    pub async fn insert_inspection(
        &self,
        conn: &mut sqlx::PgConnection,
        i: &NewInspectionRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO quality.quality_inspections
                 (id, template_id, item_id, inspection_type, source_type, source_id,
                  sample_size, inspected_at, status, remarks)
               VALUES ($1,$2,$3,$4::inspection_type,$5,$6,$7,$8,$9::inspection_status,NULL)"#,
        )
        .bind(i.id).bind(i.template_id).bind(i.item_id).bind(i.inspection_type)
        .bind(i.source_type).bind(i.source_id).bind(i.sample_size).bind(i.inspected_at).bind(i.status)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// An inspection's verdict, as text. `Ok(None)` = not visible in the caller's scope.
    ///
    /// ID-only: no tenant argument. The scoped read helper rides the request-dedicated connection when
    /// the composing service bound one (carrying the decorator's fence variables), plainly on the pool
    /// otherwise — a cited inspection must be visible in the caller's scope or it reads as not found
    /// (ADR-0029).
    pub async fn find_status(&self, pool: &PgPool, inspection_id: Uuid) -> Result<Option<String>, sqlx::Error> {
        fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar(
                "SELECT status::text FROM quality.quality_inspections WHERE id=$1 AND (metadata->>'deleted_at') IS NULL")
                .bind(inspection_id),
        )
        .await
    }
}

backbone_core::impl_crud_repository!(QualityInspectionRepository, QualityInspection, soft_delete);
