//! Validator for NonConformance entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<NonConformance>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::NonConformance;

/// Validator type alias for NonConformance entities.
pub type NonConformanceValidator = EntityValidator<NonConformance>;

/// Build a validator for NonConformance with all schema-defined field rules.
pub fn non_conformance_validator() -> NonConformanceValidator {
    EntityValidator::new()
        .rule(RequiredString::new("subject", |e: &NonConformance| &e.subject))
        .rule(OptionalNotBlank::new("description", |e: &NonConformance| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
