//! Validator for QualityProcedure entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<QualityProcedure>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::QualityProcedure;

/// Validator type alias for QualityProcedure entities.
pub type QualityProcedureValidator = EntityValidator<QualityProcedure>;

/// Build a validator for QualityProcedure with all schema-defined field rules.
pub fn quality_procedure_validator() -> QualityProcedureValidator {
    EntityValidator::new()
        .rule(RequiredString::new("procedure_name", |e: &QualityProcedure| &e.procedure_name))
        .rule(OptionalNotBlank::new("description", |e: &QualityProcedure| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
