//! Validator for QualityInspectionParameter entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<QualityInspectionParameter>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::QualityInspectionParameter;

/// Validator type alias for QualityInspectionParameter entities.
pub type QualityInspectionParameterValidator = EntityValidator<QualityInspectionParameter>;

/// Build a validator for QualityInspectionParameter with all schema-defined field rules.
pub fn quality_inspection_parameter_validator() -> QualityInspectionParameterValidator {
    EntityValidator::new()
        .rule(RequiredString::new("parameter_name", |e: &QualityInspectionParameter| &e.parameter_name))
        .rule(OptionalNotBlank::new("spec_text", |e: &QualityInspectionParameter| e.spec_text.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
