//! Validator for QualityInspectionTemplate entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<QualityInspectionTemplate>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::QualityInspectionTemplate;

/// Validator type alias for QualityInspectionTemplate entities.
pub type QualityInspectionTemplateValidator = EntityValidator<QualityInspectionTemplate>;

/// Build a validator for QualityInspectionTemplate with all schema-defined field rules.
pub fn quality_inspection_template_validator() -> QualityInspectionTemplateValidator {
    EntityValidator::new()
        .rule(RequiredString::new("template_name", |e: &QualityInspectionTemplate| &e.template_name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
