//! Validator for QualityAction entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<QualityAction>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::QualityAction;

/// Validator type alias for QualityAction entities.
pub type QualityActionValidator = EntityValidator<QualityAction>;

/// Build a validator for QualityAction with all schema-defined field rules.
pub fn quality_action_validator() -> QualityActionValidator {
    EntityValidator::new()
        .rule(RequiredString::new("description", |e: &QualityAction| &e.description))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
