//! Validator for QualityInspection entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<QualityInspection>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank};
use crate::domain::entity::QualityInspection;

/// Validator type alias for QualityInspection entities.
pub type QualityInspectionValidator = EntityValidator<QualityInspection>;

/// Build a validator for QualityInspection with all schema-defined field rules.
pub fn quality_inspection_validator() -> QualityInspectionValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("source_type", |e: &QualityInspection| e.source_type.as_deref()))
        .rule(NonNegative::new("sample_size", |e: &QualityInspection| e.sample_size as i64))
        .rule(OptionalNotBlank::new("remarks", |e: &QualityInspection| e.remarks.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
