//! Validator for QualityInspectionReading entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<QualityInspectionReading>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::QualityInspectionReading;

/// Validator type alias for QualityInspectionReading entities.
pub type QualityInspectionReadingValidator = EntityValidator<QualityInspectionReading>;

/// Build a validator for QualityInspectionReading with all schema-defined field rules.
pub fn quality_inspection_reading_validator() -> QualityInspectionReadingValidator {
    EntityValidator::new()
        .rule(RequiredString::new("parameter_name", |e: &QualityInspectionReading| &e.parameter_name))
        .rule(OptionalNotBlank::new("remarks", |e: &QualityInspectionReading| e.remarks.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
