//! Domain Entities
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod non_conformance;
pub mod quality_action;
pub mod quality_inspection;
pub mod quality_inspection_reading;
pub mod quality_inspection_template;
pub mod quality_inspection_parameter;
pub mod quality_procedure;
pub mod non_conformance_severity;
pub mod non_conformance_status;
pub mod quality_action_type;
pub mod quality_action_status;
pub mod inspection_type;
pub mod inspection_status;
pub mod reading_result;

// Re-exports
pub use non_conformance::NonConformance;
pub use non_conformance::NonConformanceBuilder;
pub use non_conformance::NonConformanceId;
pub use quality_action::QualityAction;
pub use quality_action::QualityActionBuilder;
pub use quality_action::QualityActionId;
pub use quality_inspection::QualityInspection;
pub use quality_inspection::QualityInspectionBuilder;
pub use quality_inspection::QualityInspectionId;
pub use quality_inspection_reading::QualityInspectionReading;
pub use quality_inspection_reading::QualityInspectionReadingBuilder;
pub use quality_inspection_reading::QualityInspectionReadingId;
pub use quality_inspection_template::QualityInspectionTemplate;
pub use quality_inspection_template::QualityInspectionTemplateBuilder;
pub use quality_inspection_template::QualityInspectionTemplateId;
pub use quality_inspection_parameter::QualityInspectionParameter;
pub use quality_inspection_parameter::QualityInspectionParameterBuilder;
pub use quality_inspection_parameter::QualityInspectionParameterId;
pub use quality_procedure::QualityProcedure;
pub use quality_procedure::QualityProcedureBuilder;
pub use quality_procedure::QualityProcedureId;
pub use non_conformance_severity::NonConformanceSeverity;
pub use non_conformance_status::NonConformanceStatus;
pub use quality_action_type::QualityActionType;
pub use quality_action_status::QualityActionStatus;
pub use inspection_type::InspectionType;
pub use inspection_status::InspectionStatus;
pub use reading_result::ReadingResult;

// ==========================================================================
// Entity Trait
// ==========================================================================

use std::fmt::Debug;

/// Trait for domain entities
///
/// All generated entities implement this trait, providing
/// a common interface for working with domain objects.
pub trait Entity: Debug + Clone {
    /// The type of the entity's unique identifier
    type Id: Debug + Clone + PartialEq;

    /// Get the entity's unique identifier
    fn entity_id(&self) -> &Self::Id;

    /// Get the entity type name
    fn entity_type() -> &'static str;
}

// ==========================================================================
// Audit Metadata
// ==========================================================================

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

/// Audit metadata stored as JSONB in the database
///
/// This struct consolidates audit fields (timestamps and actors) into a single
/// JSONB column for efficient storage and flexible querying.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct AuditMetadata {
    /// Timestamp when the record was created
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was last updated
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was soft-deleted
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<DateTime<Utc>>,

    /// User ID who created the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Uuid>,

    /// User ID who last updated the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Uuid>,

    /// User ID who deleted the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_by: Option<Uuid>,
}

impl AuditMetadata {
    /// Create new audit metadata with created_at set to now
    pub fn new() -> Self {
        Self {
            created_at: Some(Utc::now()),
            ..Default::default()
        }
    }

    /// Create with creator ID
    pub fn with_creator(creator_id: Uuid) -> Self {
        Self {
            created_at: Some(Utc::now()),
            created_by: Some(creator_id),
            ..Default::default()
        }
    }

    /// Touch the record (update updated_at)
    pub fn touch(&mut self) {
        self.updated_at = Some(Utc::now());
    }

    /// Touch with updater ID
    pub fn touch_by(&mut self, updater_id: Uuid) {
        self.updated_at = Some(Utc::now());
        self.updated_by = Some(updater_id);
    }

    /// Soft delete the record
    pub fn soft_delete(&mut self) {
        self.deleted_at = Some(Utc::now());
    }

    /// Soft delete with deleter ID
    pub fn soft_delete_by(&mut self, deleter_id: Uuid) {
        self.deleted_at = Some(Utc::now());
        self.deleted_by = Some(deleter_id);
    }

    /// Restore a soft-deleted record
    pub fn restore(&mut self) {
        self.deleted_at = None;
        self.deleted_by = None;
    }

    /// Check if record is deleted
    pub fn is_deleted(&self) -> bool {
        self.deleted_at.is_some()
    }

    /// Check if record is active (not deleted)
    pub fn is_active(&self) -> bool {
        self.deleted_at.is_none()
    }
}
