//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod non_conformance_auth;
pub mod quality_action_auth;
pub mod quality_inspection_auth;
pub mod quality_inspection_reading_auth;
pub mod quality_inspection_template_auth;
pub mod quality_inspection_parameter_auth;
pub mod quality_procedure_auth;

pub use non_conformance_auth::{NonConformancePolicy, NonConformanceGuard, NonConformanceServiceGuard};
pub use quality_action_auth::{QualityActionPolicy, QualityActionGuard, QualityActionServiceGuard};
pub use quality_inspection_auth::{QualityInspectionPolicy, QualityInspectionGuard, QualityInspectionServiceGuard};
pub use quality_inspection_reading_auth::{QualityInspectionReadingPolicy, QualityInspectionReadingGuard, QualityInspectionReadingServiceGuard};
pub use quality_inspection_template_auth::{QualityInspectionTemplatePolicy, QualityInspectionTemplateGuard, QualityInspectionTemplateServiceGuard};
pub use quality_inspection_parameter_auth::{QualityInspectionParameterPolicy, QualityInspectionParameterGuard, QualityInspectionParameterServiceGuard};
pub use quality_procedure_auth::{QualityProcedurePolicy, QualityProcedureGuard, QualityProcedureServiceGuard};

// <<< CUSTOM
// END CUSTOM
