//! Auth configuration for NonConformance handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<NonConformance>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::NonConformanceService;
use crate::domain::entity::NonConformance;

/// Permission string constants for NonConformance operations.
pub mod permissions {
    pub const LIST:        &str = "non_conformance:list";
    pub const READ:        &str = "non_conformance:read";
    pub const CREATE:      &str = "non_conformance:create";
    pub const UPDATE:      &str = "non_conformance:update";
    pub const DELETE:      &str = "non_conformance:delete";
    pub const RESTORE:     &str = "non_conformance:restore";
    pub const TRASH:       &str = "non_conformance:trash";
    pub const EMPTY_TRASH: &str = "non_conformance:empty_trash";
    pub const BULK_CREATE: &str = "non_conformance:bulk_create";
    pub const UPSERT:      &str = "non_conformance:upsert";
}

/// Resource policy for NonConformance — maps CRUD actions to permission strings.
pub struct NonConformancePolicy;

#[async_trait]
impl ResourcePolicy<NonConformance> for NonConformancePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &NonConformance,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for NonConformance handlers.
///
/// Wraps `NonConformanceService` and checks `NonConformancePolicy` before delegating.
pub type NonConformanceGuard = PermissionGuard<NonConformance>;

/// Service-integrated permission guard for NonConformance (for use in generated handlers).
pub type NonConformanceServiceGuard = ServicePermissionGuard<NonConformance, NonConformanceService, NonConformancePolicy>;

// <<< CUSTOM
// END CUSTOM
