//! Auth configuration for QualityInspection handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<QualityInspection>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::QualityInspectionService;
use crate::domain::entity::QualityInspection;

/// Permission string constants for QualityInspection operations.
pub mod permissions {
    pub const LIST:        &str = "quality_inspection:list";
    pub const READ:        &str = "quality_inspection:read";
    pub const CREATE:      &str = "quality_inspection:create";
    pub const UPDATE:      &str = "quality_inspection:update";
    pub const DELETE:      &str = "quality_inspection:delete";
    pub const RESTORE:     &str = "quality_inspection:restore";
    pub const TRASH:       &str = "quality_inspection:trash";
    pub const EMPTY_TRASH: &str = "quality_inspection:empty_trash";
    pub const BULK_CREATE: &str = "quality_inspection:bulk_create";
    pub const UPSERT:      &str = "quality_inspection:upsert";
}

/// Resource policy for QualityInspection — maps CRUD actions to permission strings.
pub struct QualityInspectionPolicy;

#[async_trait]
impl ResourcePolicy<QualityInspection> for QualityInspectionPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &QualityInspection,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for QualityInspection handlers.
///
/// Wraps `QualityInspectionService` and checks `QualityInspectionPolicy` before delegating.
pub type QualityInspectionGuard = PermissionGuard<QualityInspection>;

/// Service-integrated permission guard for QualityInspection (for use in generated handlers).
pub type QualityInspectionServiceGuard = ServicePermissionGuard<QualityInspection, QualityInspectionService, QualityInspectionPolicy>;

// <<< CUSTOM
// END CUSTOM
