//! Auth configuration for QualityInspectionParameter handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<QualityInspectionParameter>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::QualityInspectionParameterService;
use crate::domain::entity::QualityInspectionParameter;

/// Permission string constants for QualityInspectionParameter operations.
pub mod permissions {
    pub const LIST:        &str = "quality_inspection_parameter:list";
    pub const READ:        &str = "quality_inspection_parameter:read";
    pub const CREATE:      &str = "quality_inspection_parameter:create";
    pub const UPDATE:      &str = "quality_inspection_parameter:update";
    pub const DELETE:      &str = "quality_inspection_parameter:delete";
    pub const RESTORE:     &str = "quality_inspection_parameter:restore";
    pub const TRASH:       &str = "quality_inspection_parameter:trash";
    pub const EMPTY_TRASH: &str = "quality_inspection_parameter:empty_trash";
    pub const BULK_CREATE: &str = "quality_inspection_parameter:bulk_create";
    pub const UPSERT:      &str = "quality_inspection_parameter:upsert";
}

/// Resource policy for QualityInspectionParameter — maps CRUD actions to permission strings.
pub struct QualityInspectionParameterPolicy;

#[async_trait]
impl ResourcePolicy<QualityInspectionParameter> for QualityInspectionParameterPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &QualityInspectionParameter,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for QualityInspectionParameter handlers.
///
/// Wraps `QualityInspectionParameterService` and checks `QualityInspectionParameterPolicy` before delegating.
pub type QualityInspectionParameterGuard = PermissionGuard<QualityInspectionParameter>;

/// Service-integrated permission guard for QualityInspectionParameter (for use in generated handlers).
pub type QualityInspectionParameterServiceGuard = ServicePermissionGuard<QualityInspectionParameter, QualityInspectionParameterService, QualityInspectionParameterPolicy>;

// <<< CUSTOM
// END CUSTOM
