//! Auth configuration for QualityInspectionReading handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<QualityInspectionReading>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::QualityInspectionReadingService;
use crate::domain::entity::QualityInspectionReading;

/// Permission string constants for QualityInspectionReading operations.
pub mod permissions {
    pub const LIST:        &str = "quality_inspection_reading:list";
    pub const READ:        &str = "quality_inspection_reading:read";
    pub const CREATE:      &str = "quality_inspection_reading:create";
    pub const UPDATE:      &str = "quality_inspection_reading:update";
    pub const DELETE:      &str = "quality_inspection_reading:delete";
    pub const RESTORE:     &str = "quality_inspection_reading:restore";
    pub const TRASH:       &str = "quality_inspection_reading:trash";
    pub const EMPTY_TRASH: &str = "quality_inspection_reading:empty_trash";
    pub const BULK_CREATE: &str = "quality_inspection_reading:bulk_create";
    pub const UPSERT:      &str = "quality_inspection_reading:upsert";
}

/// Resource policy for QualityInspectionReading — maps CRUD actions to permission strings.
pub struct QualityInspectionReadingPolicy;

#[async_trait]
impl ResourcePolicy<QualityInspectionReading> for QualityInspectionReadingPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &QualityInspectionReading,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for QualityInspectionReading handlers.
///
/// Wraps `QualityInspectionReadingService` and checks `QualityInspectionReadingPolicy` before delegating.
pub type QualityInspectionReadingGuard = PermissionGuard<QualityInspectionReading>;

/// Service-integrated permission guard for QualityInspectionReading (for use in generated handlers).
pub type QualityInspectionReadingServiceGuard = ServicePermissionGuard<QualityInspectionReading, QualityInspectionReadingService, QualityInspectionReadingPolicy>;

// <<< CUSTOM
// END CUSTOM
