//! Auth configuration for QualityAction handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<QualityAction>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::QualityActionService;
use crate::domain::entity::QualityAction;

/// Permission string constants for QualityAction operations.
pub mod permissions {
    pub const LIST:        &str = "quality_action:list";
    pub const READ:        &str = "quality_action:read";
    pub const CREATE:      &str = "quality_action:create";
    pub const UPDATE:      &str = "quality_action:update";
    pub const DELETE:      &str = "quality_action:delete";
    pub const RESTORE:     &str = "quality_action:restore";
    pub const TRASH:       &str = "quality_action:trash";
    pub const EMPTY_TRASH: &str = "quality_action:empty_trash";
    pub const BULK_CREATE: &str = "quality_action:bulk_create";
    pub const UPSERT:      &str = "quality_action:upsert";
}

/// Resource policy for QualityAction — maps CRUD actions to permission strings.
pub struct QualityActionPolicy;

#[async_trait]
impl ResourcePolicy<QualityAction> for QualityActionPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &QualityAction,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for QualityAction handlers.
///
/// Wraps `QualityActionService` and checks `QualityActionPolicy` before delegating.
pub type QualityActionGuard = PermissionGuard<QualityAction>;

/// Service-integrated permission guard for QualityAction (for use in generated handlers).
pub type QualityActionServiceGuard = ServicePermissionGuard<QualityAction, QualityActionService, QualityActionPolicy>;

// <<< CUSTOM
// END CUSTOM
