//! Auth configuration for QualityProcedure handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<QualityProcedure>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::QualityProcedureService;
use crate::domain::entity::QualityProcedure;

/// Permission string constants for QualityProcedure operations.
pub mod permissions {
    pub const LIST:        &str = "quality_procedure:list";
    pub const READ:        &str = "quality_procedure:read";
    pub const CREATE:      &str = "quality_procedure:create";
    pub const UPDATE:      &str = "quality_procedure:update";
    pub const DELETE:      &str = "quality_procedure:delete";
    pub const RESTORE:     &str = "quality_procedure:restore";
    pub const TRASH:       &str = "quality_procedure:trash";
    pub const EMPTY_TRASH: &str = "quality_procedure:empty_trash";
    pub const BULK_CREATE: &str = "quality_procedure:bulk_create";
    pub const UPSERT:      &str = "quality_procedure:upsert";
}

/// Resource policy for QualityProcedure — maps CRUD actions to permission strings.
pub struct QualityProcedurePolicy;

#[async_trait]
impl ResourcePolicy<QualityProcedure> for QualityProcedurePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &QualityProcedure,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for QualityProcedure handlers.
///
/// Wraps `QualityProcedureService` and checks `QualityProcedurePolicy` before delegating.
pub type QualityProcedureGuard = PermissionGuard<QualityProcedure>;

/// Service-integrated permission guard for QualityProcedure (for use in generated handlers).
pub type QualityProcedureServiceGuard = ServicePermissionGuard<QualityProcedure, QualityProcedureService, QualityProcedurePolicy>;

// <<< CUSTOM
// END CUSTOM
