//! Auth configuration for QualityInspectionTemplate handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<QualityInspectionTemplate>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::QualityInspectionTemplateService;
use crate::domain::entity::QualityInspectionTemplate;

/// Permission string constants for QualityInspectionTemplate operations.
pub mod permissions {
    pub const LIST:        &str = "quality_inspection_template:list";
    pub const READ:        &str = "quality_inspection_template:read";
    pub const CREATE:      &str = "quality_inspection_template:create";
    pub const UPDATE:      &str = "quality_inspection_template:update";
    pub const DELETE:      &str = "quality_inspection_template:delete";
    pub const RESTORE:     &str = "quality_inspection_template:restore";
    pub const TRASH:       &str = "quality_inspection_template:trash";
    pub const EMPTY_TRASH: &str = "quality_inspection_template:empty_trash";
    pub const BULK_CREATE: &str = "quality_inspection_template:bulk_create";
    pub const UPSERT:      &str = "quality_inspection_template:upsert";
}

/// Resource policy for QualityInspectionTemplate — maps CRUD actions to permission strings.
pub struct QualityInspectionTemplatePolicy;

#[async_trait]
impl ResourcePolicy<QualityInspectionTemplate> for QualityInspectionTemplatePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &QualityInspectionTemplate,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for QualityInspectionTemplate handlers.
///
/// Wraps `QualityInspectionTemplateService` and checks `QualityInspectionTemplatePolicy` before delegating.
pub type QualityInspectionTemplateGuard = PermissionGuard<QualityInspectionTemplate>;

/// Service-integrated permission guard for QualityInspectionTemplate (for use in generated handlers).
pub type QualityInspectionTemplateServiceGuard = ServicePermissionGuard<QualityInspectionTemplate, QualityInspectionTemplateService, QualityInspectionTemplatePolicy>;

// <<< CUSTOM
// END CUSTOM
