//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod non_conformance_api_test;
pub mod quality_action_api_test;
pub mod quality_inspection_api_test;
pub mod quality_inspection_reading_api_test;
pub mod quality_inspection_template_api_test;
pub mod quality_inspection_parameter_api_test;
pub mod quality_procedure_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use non_conformance_api_test::*;
pub use quality_action_api_test::*;
pub use quality_inspection_api_test::*;
pub use quality_inspection_reading_api_test::*;
pub use quality_inspection_template_api_test::*;
pub use quality_inspection_parameter_api_test::*;
pub use quality_procedure_api_test::*;
