//! NonConformance API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the NonConformance CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// NONCONFORMANCE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for NonConformance
pub struct NonConformanceTestData;

impl TestDataGenerator for NonConformanceTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "subject": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "source_inspection_id": null,
            "item_id": null,
            "severity": "low",
            "status": "open",
            "description": null,
            "opened_at": now,
            "closed_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "subject": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "source_inspection_id": null,
            "item_id": null,
            "severity": "low",
            "status": "open",
            "description": null,
            "opened_at": now,
            "closed_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// NONCONFORMANCE API TEST
// ============================================================================

/// NonConformance API test suite
pub struct NonConformanceApiTest {
    inner: GenericCrudTest<NonConformanceTestData>,
}

impl NonConformanceApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/non_conformances", "NonConformance");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, NonConformanceTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for NonConformanceApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_non_conformance_crud() {
        let mut test = NonConformanceApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add NonConformance specific tests here
// <<< CUSTOM TESTS END >>>
