//! Quality Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::NonConformanceService;
use crate::application::service::QualityActionService;
use crate::application::service::QualityInspectionService;
use crate::application::service::QualityInspectionReadingService;
use crate::application::service::QualityInspectionTemplateService;
use crate::application::service::QualityInspectionParameterService;
use crate::application::service::QualityProcedureService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// NonConformance service
    pub non_conformance_service: Arc<NonConformanceService>,
    /// QualityAction service
    pub quality_action_service: Arc<QualityActionService>,
    /// QualityInspection service
    pub quality_inspection_service: Arc<QualityInspectionService>,
    /// QualityInspectionReading service
    pub quality_inspection_reading_service: Arc<QualityInspectionReadingService>,
    /// QualityInspectionTemplate service
    pub quality_inspection_template_service: Arc<QualityInspectionTemplateService>,
    /// QualityInspectionParameter service
    pub quality_inspection_parameter_service: Arc<QualityInspectionParameterService>,
    /// QualityProcedure service
    pub quality_procedure_service: Arc<QualityProcedureService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        non_conformance_service: Arc<NonConformanceService>,
        quality_action_service: Arc<QualityActionService>,
        quality_inspection_service: Arc<QualityInspectionService>,
        quality_inspection_reading_service: Arc<QualityInspectionReadingService>,
        quality_inspection_template_service: Arc<QualityInspectionTemplateService>,
        quality_inspection_parameter_service: Arc<QualityInspectionParameterService>,
        quality_procedure_service: Arc<QualityProcedureService>
    ) -> Self {
        Self {
            non_conformance_service,
            quality_action_service,
            quality_inspection_service,
            quality_inspection_reading_service,
            quality_inspection_template_service,
            quality_inspection_parameter_service,
            quality_procedure_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::QualityModule) -> Self {
        Self {
            non_conformance_service: module.non_conformance_service.clone(),
            quality_action_service: module.quality_action_service.clone(),
            quality_inspection_service: module.quality_inspection_service.clone(),
            quality_inspection_reading_service: module.quality_inspection_reading_service.clone(),
            quality_inspection_template_service: module.quality_inspection_template_service.clone(),
            quality_inspection_parameter_service: module.quality_inspection_parameter_service.clone(),
            quality_procedure_service: module.quality_procedure_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    non_conformance_service: Option<Arc<NonConformanceService>>,
    quality_action_service: Option<Arc<QualityActionService>>,
    quality_inspection_service: Option<Arc<QualityInspectionService>>,
    quality_inspection_reading_service: Option<Arc<QualityInspectionReadingService>>,
    quality_inspection_template_service: Option<Arc<QualityInspectionTemplateService>>,
    quality_inspection_parameter_service: Option<Arc<QualityInspectionParameterService>>,
    quality_procedure_service: Option<Arc<QualityProcedureService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the NonConformance service.
    pub fn with_non_conformance_service(mut self, service: Arc<NonConformanceService>) -> Self {
        self.non_conformance_service = Some(service);
        self
    }

    /// Set the QualityAction service.
    pub fn with_quality_action_service(mut self, service: Arc<QualityActionService>) -> Self {
        self.quality_action_service = Some(service);
        self
    }

    /// Set the QualityInspection service.
    pub fn with_quality_inspection_service(mut self, service: Arc<QualityInspectionService>) -> Self {
        self.quality_inspection_service = Some(service);
        self
    }

    /// Set the QualityInspectionReading service.
    pub fn with_quality_inspection_reading_service(mut self, service: Arc<QualityInspectionReadingService>) -> Self {
        self.quality_inspection_reading_service = Some(service);
        self
    }

    /// Set the QualityInspectionTemplate service.
    pub fn with_quality_inspection_template_service(mut self, service: Arc<QualityInspectionTemplateService>) -> Self {
        self.quality_inspection_template_service = Some(service);
        self
    }

    /// Set the QualityInspectionParameter service.
    pub fn with_quality_inspection_parameter_service(mut self, service: Arc<QualityInspectionParameterService>) -> Self {
        self.quality_inspection_parameter_service = Some(service);
        self
    }

    /// Set the QualityProcedure service.
    pub fn with_quality_procedure_service(mut self, service: Arc<QualityProcedureService>) -> Self {
        self.quality_procedure_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            non_conformance_service: self.non_conformance_service.expect("non_conformance_service is required"),
            quality_action_service: self.quality_action_service.expect("quality_action_service is required"),
            quality_inspection_service: self.quality_inspection_service.expect("quality_inspection_service is required"),
            quality_inspection_reading_service: self.quality_inspection_reading_service.expect("quality_inspection_reading_service is required"),
            quality_inspection_template_service: self.quality_inspection_template_service.expect("quality_inspection_template_service is required"),
            quality_inspection_parameter_service: self.quality_inspection_parameter_service.expect("quality_inspection_parameter_service is required"),
            quality_procedure_service: self.quality_procedure_service.expect("quality_procedure_service is required"),
        }
    }
}
