//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    non_conformance_handler::create_non_conformance_routes,
    quality_action_handler::create_quality_action_routes,
    quality_inspection_handler::create_quality_inspection_routes,
    quality_inspection_reading_handler::create_quality_inspection_reading_routes,
    quality_inspection_template_handler::create_quality_inspection_template_routes,
    quality_inspection_parameter_handler::create_quality_inspection_parameter_routes,
    quality_procedure_handler::create_quality_procedure_routes,
};

use crate::application::service::{
    NonConformanceService,
    QualityActionService,
    QualityInspectionService,
    QualityInspectionReadingService,
    QualityInspectionTemplateService,
    QualityInspectionParameterService,
    QualityProcedureService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub non_conformance: Arc<NonConformanceService>,
    pub quality_action: Arc<QualityActionService>,
    pub quality_inspection: Arc<QualityInspectionService>,
    pub quality_inspection_reading: Arc<QualityInspectionReadingService>,
    pub quality_inspection_template: Arc<QualityInspectionTemplateService>,
    pub quality_inspection_parameter: Arc<QualityInspectionParameterService>,
    pub quality_procedure: Arc<QualityProcedureService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // NonConformance routes (12 Backbone endpoints)
        .merge(create_non_conformance_routes(services.non_conformance))
        // QualityAction routes (12 Backbone endpoints)
        .merge(create_quality_action_routes(services.quality_action))
        // QualityInspection routes (12 Backbone endpoints)
        .merge(create_quality_inspection_routes(services.quality_inspection))
        // QualityInspectionReading routes (12 Backbone endpoints)
        .merge(create_quality_inspection_reading_routes(services.quality_inspection_reading))
        // QualityInspectionTemplate routes (12 Backbone endpoints)
        .merge(create_quality_inspection_template_routes(services.quality_inspection_template))
        // QualityInspectionParameter routes (12 Backbone endpoints)
        .merge(create_quality_inspection_parameter_routes(services.quality_inspection_parameter))
        // QualityProcedure routes (12 Backbone endpoints)
        .merge(create_quality_procedure_routes(services.quality_procedure))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn non_conformance_routes(service: Arc<NonConformanceService>) -> Router {
        create_non_conformance_routes(service)
    }

    pub fn quality_action_routes(service: Arc<QualityActionService>) -> Router {
        create_quality_action_routes(service)
    }

    pub fn quality_inspection_routes(service: Arc<QualityInspectionService>) -> Router {
        create_quality_inspection_routes(service)
    }

    pub fn quality_inspection_reading_routes(service: Arc<QualityInspectionReadingService>) -> Router {
        create_quality_inspection_reading_routes(service)
    }

    pub fn quality_inspection_template_routes(service: Arc<QualityInspectionTemplateService>) -> Router {
        create_quality_inspection_template_routes(service)
    }

    pub fn quality_inspection_parameter_routes(service: Arc<QualityInspectionParameterService>) -> Router {
        create_quality_inspection_parameter_routes(service)
    }

    pub fn quality_procedure_routes(service: Arc<QualityProcedureService>) -> Router {
        create_quality_procedure_routes(service)
    }

}
