//! Public events for Quality module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// NONCONFORMANCE EVENTS
// ============================================================================

/// Event published when a NonConformance is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NonConformanceCreatedEvent {
    pub id: NonConformanceId,
    pub data: NonConformanceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a NonConformance is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NonConformanceUpdatedEvent {
    pub id: NonConformanceId,
    pub data: NonConformanceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a NonConformance is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NonConformanceDeletedEvent {
    pub id: NonConformanceId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// QUALITYACTION EVENTS
// ============================================================================

/// Event published when a QualityAction is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityActionCreatedEvent {
    pub id: QualityActionId,
    pub data: QualityActionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a QualityAction is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityActionUpdatedEvent {
    pub id: QualityActionId,
    pub data: QualityActionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a QualityAction is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityActionDeletedEvent {
    pub id: QualityActionId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// QUALITYINSPECTION EVENTS
// ============================================================================

/// Event published when a QualityInspection is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionCreatedEvent {
    pub id: QualityInspectionId,
    pub data: QualityInspectionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a QualityInspection is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionUpdatedEvent {
    pub id: QualityInspectionId,
    pub data: QualityInspectionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a QualityInspection is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionDeletedEvent {
    pub id: QualityInspectionId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// QUALITYINSPECTIONREADING EVENTS
// ============================================================================

/// Event published when a QualityInspectionReading is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionReadingCreatedEvent {
    pub id: QualityInspectionReadingId,
    pub data: QualityInspectionReadingDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a QualityInspectionReading is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionReadingUpdatedEvent {
    pub id: QualityInspectionReadingId,
    pub data: QualityInspectionReadingDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a QualityInspectionReading is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionReadingDeletedEvent {
    pub id: QualityInspectionReadingId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// QUALITYINSPECTIONTEMPLATE EVENTS
// ============================================================================

/// Event published when a QualityInspectionTemplate is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionTemplateCreatedEvent {
    pub id: QualityInspectionTemplateId,
    pub data: QualityInspectionTemplateDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a QualityInspectionTemplate is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionTemplateUpdatedEvent {
    pub id: QualityInspectionTemplateId,
    pub data: QualityInspectionTemplateDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a QualityInspectionTemplate is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionTemplateDeletedEvent {
    pub id: QualityInspectionTemplateId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// QUALITYINSPECTIONPARAMETER EVENTS
// ============================================================================

/// Event published when a QualityInspectionParameter is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionParameterCreatedEvent {
    pub id: QualityInspectionParameterId,
    pub data: QualityInspectionParameterDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a QualityInspectionParameter is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionParameterUpdatedEvent {
    pub id: QualityInspectionParameterId,
    pub data: QualityInspectionParameterDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a QualityInspectionParameter is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionParameterDeletedEvent {
    pub id: QualityInspectionParameterId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// QUALITYPROCEDURE EVENTS
// ============================================================================

/// Event published when a QualityProcedure is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityProcedureCreatedEvent {
    pub id: QualityProcedureId,
    pub data: QualityProcedureDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a QualityProcedure is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityProcedureUpdatedEvent {
    pub id: QualityProcedureId,
    pub data: QualityProcedureDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a QualityProcedure is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityProcedureDeletedEvent {
    pub id: QualityProcedureId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Quality module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum QualityEvent {
    NonConformanceCreated(NonConformanceCreatedEvent),
    NonConformanceUpdated(NonConformanceUpdatedEvent),
    NonConformanceDeleted(NonConformanceDeletedEvent),
    QualityActionCreated(QualityActionCreatedEvent),
    QualityActionUpdated(QualityActionUpdatedEvent),
    QualityActionDeleted(QualityActionDeletedEvent),
    QualityInspectionCreated(QualityInspectionCreatedEvent),
    QualityInspectionUpdated(QualityInspectionUpdatedEvent),
    QualityInspectionDeleted(QualityInspectionDeletedEvent),
    QualityInspectionReadingCreated(QualityInspectionReadingCreatedEvent),
    QualityInspectionReadingUpdated(QualityInspectionReadingUpdatedEvent),
    QualityInspectionReadingDeleted(QualityInspectionReadingDeletedEvent),
    QualityInspectionTemplateCreated(QualityInspectionTemplateCreatedEvent),
    QualityInspectionTemplateUpdated(QualityInspectionTemplateUpdatedEvent),
    QualityInspectionTemplateDeleted(QualityInspectionTemplateDeletedEvent),
    QualityInspectionParameterCreated(QualityInspectionParameterCreatedEvent),
    QualityInspectionParameterUpdated(QualityInspectionParameterUpdatedEvent),
    QualityInspectionParameterDeleted(QualityInspectionParameterDeletedEvent),
    QualityProcedureCreated(QualityProcedureCreatedEvent),
    QualityProcedureUpdated(QualityProcedureUpdatedEvent),
    QualityProcedureDeleted(QualityProcedureDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for QualityEventMetadata {
    fn default() -> Self {
        Self {
            module: "quality",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
