//! Quality Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Quality exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use quality::exports::{NonConformanceDto, QualityQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `NonConformanceDto` - Data transfer object for NonConformance
/// - `NonConformanceSummary` - Summary view of NonConformance
/// - `NonConformanceId` - Type-safe ID wrapper
/// - `QualityActionDto` - Data transfer object for QualityAction
/// - `QualityActionSummary` - Summary view of QualityAction
/// - `QualityActionId` - Type-safe ID wrapper
/// - `QualityInspectionDto` - Data transfer object for QualityInspection
/// - `QualityInspectionSummary` - Summary view of QualityInspection
/// - `QualityInspectionId` - Type-safe ID wrapper
/// - `QualityInspectionReadingDto` - Data transfer object for QualityInspectionReading
/// - `QualityInspectionReadingSummary` - Summary view of QualityInspectionReading
/// - `QualityInspectionReadingId` - Type-safe ID wrapper
/// - `QualityInspectionTemplateDto` - Data transfer object for QualityInspectionTemplate
/// - `QualityInspectionTemplateSummary` - Summary view of QualityInspectionTemplate
/// - `QualityInspectionTemplateId` - Type-safe ID wrapper
/// - `QualityInspectionParameterDto` - Data transfer object for QualityInspectionParameter
/// - `QualityInspectionParameterSummary` - Summary view of QualityInspectionParameter
/// - `QualityInspectionParameterId` - Type-safe ID wrapper
/// - `QualityProcedureDto` - Data transfer object for QualityProcedure
/// - `QualityProcedureSummary` - Summary view of QualityProcedure
/// - `QualityProcedureId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `QualityQueryService` - Read-only queries
///
/// ## Public Events
/// - `NonConformanceCreatedEvent` - Published when NonConformance is created
/// - `NonConformanceUpdatedEvent` - Published when NonConformance is updated
/// - `NonConformanceDeletedEvent` - Published when NonConformance is deleted
/// - `QualityActionCreatedEvent` - Published when QualityAction is created
/// - `QualityActionUpdatedEvent` - Published when QualityAction is updated
/// - `QualityActionDeletedEvent` - Published when QualityAction is deleted
/// - `QualityInspectionCreatedEvent` - Published when QualityInspection is created
/// - `QualityInspectionUpdatedEvent` - Published when QualityInspection is updated
/// - `QualityInspectionDeletedEvent` - Published when QualityInspection is deleted
/// - `QualityInspectionReadingCreatedEvent` - Published when QualityInspectionReading is created
/// - `QualityInspectionReadingUpdatedEvent` - Published when QualityInspectionReading is updated
/// - `QualityInspectionReadingDeletedEvent` - Published when QualityInspectionReading is deleted
/// - `QualityInspectionTemplateCreatedEvent` - Published when QualityInspectionTemplate is created
/// - `QualityInspectionTemplateUpdatedEvent` - Published when QualityInspectionTemplate is updated
/// - `QualityInspectionTemplateDeletedEvent` - Published when QualityInspectionTemplate is deleted
/// - `QualityInspectionParameterCreatedEvent` - Published when QualityInspectionParameter is created
/// - `QualityInspectionParameterUpdatedEvent` - Published when QualityInspectionParameter is updated
/// - `QualityInspectionParameterDeletedEvent` - Published when QualityInspectionParameter is deleted
/// - `QualityProcedureCreatedEvent` - Published when QualityProcedure is created
/// - `QualityProcedureUpdatedEvent` - Published when QualityProcedure is updated
/// - `QualityProcedureDeletedEvent` - Published when QualityProcedure is deleted
pub struct ExportSummary;
