//! Public services for Quality module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Quality module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait QualityQueryService: Send + Sync {
    /// Get NonConformance by ID
    async fn get_non_conformance(&self, id: NonConformanceId) -> Result<Option<NonConformanceDto>>;

    /// Get NonConformance summary by ID
    async fn get_non_conformance_summary(&self, id: NonConformanceId) -> Result<Option<NonConformanceSummary>>;

    /// Check if NonConformance exists
    async fn non_conformance_exists(&self, id: NonConformanceId) -> Result<bool>;

    /// Get QualityAction by ID
    async fn get_quality_action(&self, id: QualityActionId) -> Result<Option<QualityActionDto>>;

    /// Get QualityAction summary by ID
    async fn get_quality_action_summary(&self, id: QualityActionId) -> Result<Option<QualityActionSummary>>;

    /// Check if QualityAction exists
    async fn quality_action_exists(&self, id: QualityActionId) -> Result<bool>;

    /// Get QualityInspection by ID
    async fn get_quality_inspection(&self, id: QualityInspectionId) -> Result<Option<QualityInspectionDto>>;

    /// Get QualityInspection summary by ID
    async fn get_quality_inspection_summary(&self, id: QualityInspectionId) -> Result<Option<QualityInspectionSummary>>;

    /// Check if QualityInspection exists
    async fn quality_inspection_exists(&self, id: QualityInspectionId) -> Result<bool>;

    /// Get QualityInspectionReading by ID
    async fn get_quality_inspection_reading(&self, id: QualityInspectionReadingId) -> Result<Option<QualityInspectionReadingDto>>;

    /// Get QualityInspectionReading summary by ID
    async fn get_quality_inspection_reading_summary(&self, id: QualityInspectionReadingId) -> Result<Option<QualityInspectionReadingSummary>>;

    /// Check if QualityInspectionReading exists
    async fn quality_inspection_reading_exists(&self, id: QualityInspectionReadingId) -> Result<bool>;

    /// Get QualityInspectionTemplate by ID
    async fn get_quality_inspection_template(&self, id: QualityInspectionTemplateId) -> Result<Option<QualityInspectionTemplateDto>>;

    /// Get QualityInspectionTemplate summary by ID
    async fn get_quality_inspection_template_summary(&self, id: QualityInspectionTemplateId) -> Result<Option<QualityInspectionTemplateSummary>>;

    /// Check if QualityInspectionTemplate exists
    async fn quality_inspection_template_exists(&self, id: QualityInspectionTemplateId) -> Result<bool>;

    /// Get QualityInspectionParameter by ID
    async fn get_quality_inspection_parameter(&self, id: QualityInspectionParameterId) -> Result<Option<QualityInspectionParameterDto>>;

    /// Get QualityInspectionParameter summary by ID
    async fn get_quality_inspection_parameter_summary(&self, id: QualityInspectionParameterId) -> Result<Option<QualityInspectionParameterSummary>>;

    /// Check if QualityInspectionParameter exists
    async fn quality_inspection_parameter_exists(&self, id: QualityInspectionParameterId) -> Result<bool>;

    /// Get QualityProcedure by ID
    async fn get_quality_procedure(&self, id: QualityProcedureId) -> Result<Option<QualityProcedureDto>>;

    /// Get QualityProcedure summary by ID
    async fn get_quality_procedure_summary(&self, id: QualityProcedureId) -> Result<Option<QualityProcedureSummary>>;

    /// Check if QualityProcedure exists
    async fn quality_procedure_exists(&self, id: QualityProcedureId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of QualityQueryService
pub struct QualityQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> QualityQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
