//! Public types for Quality module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// NONCONFORMANCE TYPES
// ============================================================================

/// Type-safe ID for NonConformance
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct NonConformanceId(pub Uuid);

impl NonConformanceId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for NonConformanceId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<NonConformanceId> for Uuid {
    fn from(id: NonConformanceId) -> Self {
        id.0
    }
}

/// Data transfer object for NonConformance
///
/// This is the public representation of NonConformance for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NonConformanceDto {
    pub id: NonConformanceId,
    pub company_id: Uuid,
    pub subject: String,
    pub source_inspection_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub severity: NonConformanceSeverity,
    pub status: NonConformanceStatus,
    pub description: Option<String>,
    pub opened_at: DateTime<Utc>,
    pub closed_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of NonConformance for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NonConformanceSummary {
    pub id: NonConformanceId,
    pub status: NonConformanceStatus,
}

/// Reference to NonConformance for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NonConformanceRef {
    pub id: NonConformanceId,
}

// ============================================================================
// QUALITYACTION TYPES
// ============================================================================

/// Type-safe ID for QualityAction
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct QualityActionId(pub Uuid);

impl QualityActionId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for QualityActionId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<QualityActionId> for Uuid {
    fn from(id: QualityActionId) -> Self {
        id.0
    }
}

/// Data transfer object for QualityAction
///
/// This is the public representation of QualityAction for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityActionDto {
    pub id: QualityActionId,
    pub company_id: Uuid,
    pub non_conformance_id: Uuid,
    pub action_type: QualityActionType,
    pub procedure_id: Option<Uuid>,
    pub status: QualityActionStatus,
    pub description: String,
    pub due_date: Option<DateTime<Utc>>,
    pub completed_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of QualityAction for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityActionSummary {
    pub id: QualityActionId,
    pub status: QualityActionStatus,
}

/// Reference to QualityAction for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityActionRef {
    pub id: QualityActionId,
}

// ============================================================================
// QUALITYINSPECTION TYPES
// ============================================================================

/// Type-safe ID for QualityInspection
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct QualityInspectionId(pub Uuid);

impl QualityInspectionId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for QualityInspectionId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<QualityInspectionId> for Uuid {
    fn from(id: QualityInspectionId) -> Self {
        id.0
    }
}

/// Data transfer object for QualityInspection
///
/// This is the public representation of QualityInspection for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionDto {
    pub id: QualityInspectionId,
    pub company_id: Uuid,
    pub template_id: Option<Uuid>,
    pub item_id: Uuid,
    pub inspection_type: InspectionType,
    pub source_type: Option<String>,
    pub source_id: Option<Uuid>,
    pub sample_size: i32,
    pub inspected_at: DateTime<Utc>,
    pub status: InspectionStatus,
    pub remarks: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of QualityInspection for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionSummary {
    pub id: QualityInspectionId,
    pub status: InspectionStatus,
}

/// Reference to QualityInspection for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionRef {
    pub id: QualityInspectionId,
}

// ============================================================================
// QUALITYINSPECTIONREADING TYPES
// ============================================================================

/// Type-safe ID for QualityInspectionReading
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct QualityInspectionReadingId(pub Uuid);

impl QualityInspectionReadingId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for QualityInspectionReadingId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<QualityInspectionReadingId> for Uuid {
    fn from(id: QualityInspectionReadingId) -> Self {
        id.0
    }
}

/// Data transfer object for QualityInspectionReading
///
/// This is the public representation of QualityInspectionReading for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionReadingDto {
    pub id: QualityInspectionReadingId,
    pub company_id: Uuid,
    pub inspection_id: Uuid,
    pub parameter_name: String,
    pub numeric: bool,
    pub reading_value: Option<Decimal>,
    pub min_value: Option<Decimal>,
    pub max_value: Option<Decimal>,
    pub manual_result: Option<bool>,
    pub result: ReadingResult,
    pub remarks: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of QualityInspectionReading for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionReadingSummary {
    pub id: QualityInspectionReadingId,
    pub parameter_name: String,
}

/// Reference to QualityInspectionReading for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionReadingRef {
    pub id: QualityInspectionReadingId,
}

// ============================================================================
// QUALITYINSPECTIONTEMPLATE TYPES
// ============================================================================

/// Type-safe ID for QualityInspectionTemplate
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct QualityInspectionTemplateId(pub Uuid);

impl QualityInspectionTemplateId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for QualityInspectionTemplateId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<QualityInspectionTemplateId> for Uuid {
    fn from(id: QualityInspectionTemplateId) -> Self {
        id.0
    }
}

/// Data transfer object for QualityInspectionTemplate
///
/// This is the public representation of QualityInspectionTemplate for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionTemplateDto {
    pub id: QualityInspectionTemplateId,
    pub company_id: Uuid,
    pub template_name: String,
    pub item_id: Option<Uuid>,
    pub is_active: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of QualityInspectionTemplate for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionTemplateSummary {
    pub id: QualityInspectionTemplateId,
    pub template_name: String,
}

/// Reference to QualityInspectionTemplate for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionTemplateRef {
    pub id: QualityInspectionTemplateId,
}

// ============================================================================
// QUALITYINSPECTIONPARAMETER TYPES
// ============================================================================

/// Type-safe ID for QualityInspectionParameter
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct QualityInspectionParameterId(pub Uuid);

impl QualityInspectionParameterId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for QualityInspectionParameterId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<QualityInspectionParameterId> for Uuid {
    fn from(id: QualityInspectionParameterId) -> Self {
        id.0
    }
}

/// Data transfer object for QualityInspectionParameter
///
/// This is the public representation of QualityInspectionParameter for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionParameterDto {
    pub id: QualityInspectionParameterId,
    pub company_id: Uuid,
    pub template_id: Uuid,
    pub parameter_name: String,
    pub numeric: bool,
    pub min_value: Option<Decimal>,
    pub max_value: Option<Decimal>,
    pub spec_text: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of QualityInspectionParameter for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionParameterSummary {
    pub id: QualityInspectionParameterId,
    pub parameter_name: String,
}

/// Reference to QualityInspectionParameter for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityInspectionParameterRef {
    pub id: QualityInspectionParameterId,
}

// ============================================================================
// QUALITYPROCEDURE TYPES
// ============================================================================

/// Type-safe ID for QualityProcedure
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct QualityProcedureId(pub Uuid);

impl QualityProcedureId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for QualityProcedureId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<QualityProcedureId> for Uuid {
    fn from(id: QualityProcedureId) -> Self {
        id.0
    }
}

/// Data transfer object for QualityProcedure
///
/// This is the public representation of QualityProcedure for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityProcedureDto {
    pub id: QualityProcedureId,
    pub company_id: Uuid,
    pub procedure_name: String,
    pub parent_procedure_id: Option<Uuid>,
    pub description: Option<String>,
    pub is_active: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of QualityProcedure for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityProcedureSummary {
    pub id: QualityProcedureId,
    pub procedure_name: String,
}

/// Reference to QualityProcedure for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QualityProcedureRef {
    pub id: QualityProcedureId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
