//! Quality Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::NonConformanceService;
pub use application::service::QualityActionService;
pub use application::service::QualityInspectionService;
pub use application::service::QualityInspectionReadingService;
pub use application::service::QualityInspectionTemplateService;
pub use application::service::QualityInspectionParameterService;
pub use application::service::QualityProcedureService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Quality module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let quality = QualityModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = quality.all_crud_routes();
/// ```
pub struct QualityModule {
    pub non_conformance_service: Arc<NonConformanceService>,
    pub quality_action_service: Arc<QualityActionService>,
    pub quality_inspection_service: Arc<QualityInspectionService>,
    pub quality_inspection_reading_service: Arc<QualityInspectionReadingService>,
    pub quality_inspection_template_service: Arc<QualityInspectionTemplateService>,
    pub quality_inspection_parameter_service: Arc<QualityInspectionParameterService>,
    pub quality_procedure_service: Arc<QualityProcedureService>,
}

impl QualityModule {
    /// Create a new module builder
    pub fn builder() -> QualityModuleBuilder {
        QualityModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_non_conformance_routes,
            create_quality_action_routes,
            create_quality_inspection_routes,
            create_quality_inspection_reading_routes,
            create_quality_inspection_template_routes,
            create_quality_inspection_parameter_routes,
            create_quality_procedure_routes,
        };

        Router::new()
            .merge(create_non_conformance_routes(self.non_conformance_service.clone()))
            .merge(create_quality_action_routes(self.quality_action_service.clone()))
            .merge(create_quality_inspection_routes(self.quality_inspection_service.clone()))
            .merge(create_quality_inspection_reading_routes(self.quality_inspection_reading_service.clone()))
            .merge(create_quality_inspection_template_routes(self.quality_inspection_template_service.clone()))
            .merge(create_quality_inspection_parameter_routes(self.quality_inspection_parameter_service.clone()))
            .merge(create_quality_procedure_routes(self.quality_procedure_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for QualityModule
pub struct QualityModuleBuilder {
    db_pool: Option<PgPool>,
}

impl QualityModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<QualityModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // NonConformance service
        let non_conformance_repository = Arc::new(NonConformanceRepository::new(db_pool.clone()));
        let non_conformance_service = Arc::new(NonConformanceService::with_repository(non_conformance_repository.clone()));

        // QualityAction service
        let quality_action_repository = Arc::new(QualityActionRepository::new(db_pool.clone()));
        let quality_action_service = Arc::new(QualityActionService::with_repository(quality_action_repository.clone()));

        // QualityInspection service
        let quality_inspection_repository = Arc::new(QualityInspectionRepository::new(db_pool.clone()));
        let quality_inspection_service = Arc::new(QualityInspectionService::with_repository(quality_inspection_repository.clone()));

        // QualityInspectionReading service
        let quality_inspection_reading_repository = Arc::new(QualityInspectionReadingRepository::new(db_pool.clone()));
        let quality_inspection_reading_service = Arc::new(QualityInspectionReadingService::with_repository(quality_inspection_reading_repository.clone()));

        // QualityInspectionTemplate service
        let quality_inspection_template_repository = Arc::new(QualityInspectionTemplateRepository::new(db_pool.clone()));
        let quality_inspection_template_service = Arc::new(QualityInspectionTemplateService::with_repository(quality_inspection_template_repository.clone()));

        // QualityInspectionParameter service
        let quality_inspection_parameter_repository = Arc::new(QualityInspectionParameterRepository::new(db_pool.clone()));
        let quality_inspection_parameter_service = Arc::new(QualityInspectionParameterService::with_repository(quality_inspection_parameter_repository.clone()));

        // QualityProcedure service
        let quality_procedure_repository = Arc::new(QualityProcedureRepository::new(db_pool.clone()));
        let quality_procedure_service = Arc::new(QualityProcedureService::with_repository(quality_procedure_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(QualityModule {
            non_conformance_service,
            quality_action_service,
            quality_inspection_service,
            quality_inspection_reading_service,
            quality_inspection_template_service,
            quality_inspection_parameter_service,
            quality_procedure_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for QualityModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
