//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod non_conformance_usecases;
pub mod quality_action_usecases;
pub mod quality_inspection_usecases;
pub mod quality_inspection_reading_usecases;
pub mod quality_inspection_template_usecases;
pub mod quality_inspection_parameter_usecases;
pub mod quality_procedure_usecases;

pub use non_conformance_usecases::{
    CreateNonConformanceUseCase, UpdateNonConformanceUseCase, GetNonConformanceUseCase,
    DeleteNonConformanceUseCase, ListNonConformanceUseCase,
};
pub use quality_action_usecases::{
    CreateQualityActionUseCase, UpdateQualityActionUseCase, GetQualityActionUseCase,
    DeleteQualityActionUseCase, ListQualityActionUseCase,
};
pub use quality_inspection_usecases::{
    CreateQualityInspectionUseCase, UpdateQualityInspectionUseCase, GetQualityInspectionUseCase,
    DeleteQualityInspectionUseCase, ListQualityInspectionUseCase,
};
pub use quality_inspection_reading_usecases::{
    CreateQualityInspectionReadingUseCase, UpdateQualityInspectionReadingUseCase, GetQualityInspectionReadingUseCase,
    DeleteQualityInspectionReadingUseCase, ListQualityInspectionReadingUseCase,
};
pub use quality_inspection_template_usecases::{
    CreateQualityInspectionTemplateUseCase, UpdateQualityInspectionTemplateUseCase, GetQualityInspectionTemplateUseCase,
    DeleteQualityInspectionTemplateUseCase, ListQualityInspectionTemplateUseCase,
};
pub use quality_inspection_parameter_usecases::{
    CreateQualityInspectionParameterUseCase, UpdateQualityInspectionParameterUseCase, GetQualityInspectionParameterUseCase,
    DeleteQualityInspectionParameterUseCase, ListQualityInspectionParameterUseCase,
};
pub use quality_procedure_usecases::{
    CreateQualityProcedureUseCase, UpdateQualityProcedureUseCase, GetQualityProcedureUseCase,
    DeleteQualityProcedureUseCase, ListQualityProcedureUseCase,
};

// <<< CUSTOM
// END CUSTOM
