//! Use case type aliases for NonConformance aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateNonConformanceDto, UpdateNonConformanceDto};
use crate::application::service::NonConformanceService;
use crate::domain::entity::NonConformance;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateNonConformanceUseCase = CreateUseCase<NonConformance, CreateNonConformanceDto, NonConformanceService>;
pub type UpdateNonConformanceUseCase = UpdateUseCase<NonConformance, UpdateNonConformanceDto, NonConformanceService>;
pub type GetNonConformanceUseCase    = GetUseCase<NonConformance, NonConformanceService>;
pub type DeleteNonConformanceUseCase = DeleteUseCase<NonConformance, NonConformanceService>;
pub type ListNonConformanceUseCase   = ListUseCase<NonConformance, NonConformanceService>;

// <<< CUSTOM
// END CUSTOM
