//! Use case type aliases for QualityProcedure aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateQualityProcedureDto, UpdateQualityProcedureDto};
use crate::application::service::QualityProcedureService;
use crate::domain::entity::QualityProcedure;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateQualityProcedureUseCase = CreateUseCase<QualityProcedure, CreateQualityProcedureDto, QualityProcedureService>;
pub type UpdateQualityProcedureUseCase = UpdateUseCase<QualityProcedure, UpdateQualityProcedureDto, QualityProcedureService>;
pub type GetQualityProcedureUseCase    = GetUseCase<QualityProcedure, QualityProcedureService>;
pub type DeleteQualityProcedureUseCase = DeleteUseCase<QualityProcedure, QualityProcedureService>;
pub type ListQualityProcedureUseCase   = ListUseCase<QualityProcedure, QualityProcedureService>;

// <<< CUSTOM
// END CUSTOM
