//! Use case type aliases for QualityInspectionTemplate aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateQualityInspectionTemplateDto, UpdateQualityInspectionTemplateDto};
use crate::application::service::QualityInspectionTemplateService;
use crate::domain::entity::QualityInspectionTemplate;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateQualityInspectionTemplateUseCase = CreateUseCase<QualityInspectionTemplate, CreateQualityInspectionTemplateDto, QualityInspectionTemplateService>;
pub type UpdateQualityInspectionTemplateUseCase = UpdateUseCase<QualityInspectionTemplate, UpdateQualityInspectionTemplateDto, QualityInspectionTemplateService>;
pub type GetQualityInspectionTemplateUseCase    = GetUseCase<QualityInspectionTemplate, QualityInspectionTemplateService>;
pub type DeleteQualityInspectionTemplateUseCase = DeleteUseCase<QualityInspectionTemplate, QualityInspectionTemplateService>;
pub type ListQualityInspectionTemplateUseCase   = ListUseCase<QualityInspectionTemplate, QualityInspectionTemplateService>;

// <<< CUSTOM
// END CUSTOM
