//! Use case type aliases for QualityInspectionParameter aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateQualityInspectionParameterDto, UpdateQualityInspectionParameterDto};
use crate::application::service::QualityInspectionParameterService;
use crate::domain::entity::QualityInspectionParameter;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateQualityInspectionParameterUseCase = CreateUseCase<QualityInspectionParameter, CreateQualityInspectionParameterDto, QualityInspectionParameterService>;
pub type UpdateQualityInspectionParameterUseCase = UpdateUseCase<QualityInspectionParameter, UpdateQualityInspectionParameterDto, QualityInspectionParameterService>;
pub type GetQualityInspectionParameterUseCase    = GetUseCase<QualityInspectionParameter, QualityInspectionParameterService>;
pub type DeleteQualityInspectionParameterUseCase = DeleteUseCase<QualityInspectionParameter, QualityInspectionParameterService>;
pub type ListQualityInspectionParameterUseCase   = ListUseCase<QualityInspectionParameter, QualityInspectionParameterService>;

// <<< CUSTOM
// END CUSTOM
