//! Use case type aliases for QualityAction aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateQualityActionDto, UpdateQualityActionDto};
use crate::application::service::QualityActionService;
use crate::domain::entity::QualityAction;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateQualityActionUseCase = CreateUseCase<QualityAction, CreateQualityActionDto, QualityActionService>;
pub type UpdateQualityActionUseCase = UpdateUseCase<QualityAction, UpdateQualityActionDto, QualityActionService>;
pub type GetQualityActionUseCase    = GetUseCase<QualityAction, QualityActionService>;
pub type DeleteQualityActionUseCase = DeleteUseCase<QualityAction, QualityActionService>;
pub type ListQualityActionUseCase   = ListUseCase<QualityAction, QualityActionService>;

// <<< CUSTOM
// END CUSTOM
