//! Use case type aliases for QualityInspection aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateQualityInspectionDto, UpdateQualityInspectionDto};
use crate::application::service::QualityInspectionService;
use crate::domain::entity::QualityInspection;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateQualityInspectionUseCase = CreateUseCase<QualityInspection, CreateQualityInspectionDto, QualityInspectionService>;
pub type UpdateQualityInspectionUseCase = UpdateUseCase<QualityInspection, UpdateQualityInspectionDto, QualityInspectionService>;
pub type GetQualityInspectionUseCase    = GetUseCase<QualityInspection, QualityInspectionService>;
pub type DeleteQualityInspectionUseCase = DeleteUseCase<QualityInspection, QualityInspectionService>;
pub type ListQualityInspectionUseCase   = ListUseCase<QualityInspection, QualityInspectionService>;

// <<< CUSTOM
// END CUSTOM
