//! Use case type aliases for QualityInspectionReading aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateQualityInspectionReadingDto, UpdateQualityInspectionReadingDto};
use crate::application::service::QualityInspectionReadingService;
use crate::domain::entity::QualityInspectionReading;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateQualityInspectionReadingUseCase = CreateUseCase<QualityInspectionReading, CreateQualityInspectionReadingDto, QualityInspectionReadingService>;
pub type UpdateQualityInspectionReadingUseCase = UpdateUseCase<QualityInspectionReading, UpdateQualityInspectionReadingDto, QualityInspectionReadingService>;
pub type GetQualityInspectionReadingUseCase    = GetUseCase<QualityInspectionReading, QualityInspectionReadingService>;
pub type DeleteQualityInspectionReadingUseCase = DeleteUseCase<QualityInspectionReading, QualityInspectionReadingService>;
pub type ListQualityInspectionReadingUseCase   = ListUseCase<QualityInspectionReading, QualityInspectionReadingService>;

// <<< CUSTOM
// END CUSTOM
