//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod non_conformance_handler;
pub mod quality_action_handler;
pub mod quality_inspection_handler;
pub mod quality_inspection_reading_handler;
pub mod quality_inspection_template_handler;
pub mod quality_inspection_parameter_handler;
pub mod quality_procedure_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use non_conformance_handler::{create_non_conformance_routes, create_non_conformance_read_routes, create_non_conformance_write_routes};
pub use quality_action_handler::{create_quality_action_routes, create_quality_action_read_routes, create_quality_action_write_routes};
pub use quality_inspection_handler::{create_quality_inspection_routes, create_quality_inspection_read_routes, create_quality_inspection_write_routes};
pub use quality_inspection_reading_handler::{create_quality_inspection_reading_routes, create_quality_inspection_reading_read_routes, create_quality_inspection_reading_write_routes};
pub use quality_inspection_template_handler::{create_quality_inspection_template_routes, create_quality_inspection_template_read_routes, create_quality_inspection_template_write_routes};
pub use quality_inspection_parameter_handler::{create_quality_inspection_parameter_routes, create_quality_inspection_parameter_read_routes, create_quality_inspection_parameter_write_routes};
pub use quality_procedure_handler::{create_quality_procedure_routes, create_quality_procedure_read_routes, create_quality_procedure_write_routes};
// <<< CUSTOM
// END CUSTOM
